package com.asiainfo.hb.bass.test.dao;

import com.asiainfo.hb.bass.test.model.FpfReq;
import com.asiainfo.hb.bass.test.model.FpfReqExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

@MapperScan
public interface FpfReqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ST.FPF_REQ
     *
     * @mbggenerated Tue Aug 22 17:11:54 CST 2017
     */
    int countByExample(FpfReqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ST.FPF_REQ
     *
     * @mbggenerated Tue Aug 22 17:11:54 CST 2017
     */
    int deleteByExample(FpfReqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ST.FPF_REQ
     *
     * @mbggenerated Tue Aug 22 17:11:54 CST 2017
     */
    int insert(FpfReq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ST.FPF_REQ
     *
     * @mbggenerated Tue Aug 22 17:11:54 CST 2017
     */
    int insertSelective(FpfReq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ST.FPF_REQ
     *
     * @mbggenerated Tue Aug 22 17:11:54 CST 2017
     */
    List<FpfReq> selectByExample(FpfReqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ST.FPF_REQ
     *
     * @mbggenerated Tue Aug 22 17:11:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") FpfReq record, @Param("example") FpfReqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ST.FPF_REQ
     *
     * @mbggenerated Tue Aug 22 17:11:54 CST 2017
     */
    int updateByExample(@Param("record") FpfReq record, @Param("example") FpfReqExample example);
}