package com.asiainfo.hb.bass.test.model;

public class FpfReq {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST.FPF_REQ.REQ_CODE
     *
     * @mbggenerated Tue Aug 22 17:11:54 CST 2017
     */
    private String reqCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST.FPF_REQ.REQ_NAME
     *
     * @mbggenerated Tue Aug 22 17:11:54 CST 2017
     */
    private String reqName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST.FPF_REQ.REQ_CHARGE
     *
     * @mbggenerated Tue Aug 22 17:11:54 CST 2017
     */
    private String reqCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST.FPF_REQ.REQ_CHARGE_ID
     *
     * @mbggenerated Tue Aug 22 17:11:54 CST 2017
     */
    private String reqChargeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST.FPF_REQ.REQ_CODE
     *
     * @return the value of ST.FPF_REQ.REQ_CODE
     *
     * @mbggenerated Tue Aug 22 17:11:54 CST 2017
     */
    public String getReqCode() {
        return reqCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST.FPF_REQ.REQ_CODE
     *
     * @param reqCode the value for ST.FPF_REQ.REQ_CODE
     *
     * @mbggenerated Tue Aug 22 17:11:54 CST 2017
     */
    public void setReqCode(String reqCode) {
        this.reqCode = reqCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST.FPF_REQ.REQ_NAME
     *
     * @return the value of ST.FPF_REQ.REQ_NAME
     *
     * @mbggenerated Tue Aug 22 17:11:54 CST 2017
     */
    public String getReqName() {
        return reqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST.FPF_REQ.REQ_NAME
     *
     * @param reqName the value for ST.FPF_REQ.REQ_NAME
     *
     * @mbggenerated Tue Aug 22 17:11:54 CST 2017
     */
    public void setReqName(String reqName) {
        this.reqName = reqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST.FPF_REQ.REQ_CHARGE
     *
     * @return the value of ST.FPF_REQ.REQ_CHARGE
     *
     * @mbggenerated Tue Aug 22 17:11:54 CST 2017
     */
    public String getReqCharge() {
        return reqCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST.FPF_REQ.REQ_CHARGE
     *
     * @param reqCharge the value for ST.FPF_REQ.REQ_CHARGE
     *
     * @mbggenerated Tue Aug 22 17:11:54 CST 2017
     */
    public void setReqCharge(String reqCharge) {
        this.reqCharge = reqCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST.FPF_REQ.REQ_CHARGE_ID
     *
     * @return the value of ST.FPF_REQ.REQ_CHARGE_ID
     *
     * @mbggenerated Tue Aug 22 17:11:54 CST 2017
     */
    public String getReqChargeId() {
        return reqChargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST.FPF_REQ.REQ_CHARGE_ID
     *
     * @param reqChargeId the value for ST.FPF_REQ.REQ_CHARGE_ID
     *
     * @mbggenerated Tue Aug 22 17:11:54 CST 2017
     */
    public void setReqChargeId(String reqChargeId) {
        this.reqChargeId = reqChargeId;
    }
}