CREATE TABLE
"ST".FPF_FILE
(
    FILE_ID VARCHAR(32) NOT NULL,
    FILE_NAME VARCHAR(128),
    FILE_CODE VARCHAR(64),
    FILE_DESC VARCHAR(1024),
    STATUS VARCHAR(16),
    FILE_PATH VARCHAR(128),
    CREATOR_ID VARCHAR(32),
    CREATOR VARCHAR(32),
    CREATE_TIME TIMESTAMP,
    APPROVER_ID VARCHAR(32),
    APPROVER VARCHAR(32),
    APPROVE_TIME TIMESTAMP,
    APPROVE_OPINION VARCHAR(256),
    REQ_ID VARCHAR(64),
    PRIMARY KEY (FILE_ID)
);
COMMENT ON TABLE FPF_FILE IS '文件表';
COMMENT ON COLUMN FPF_FILE.FILE_ID IS '文件ID';
COMMENT ON COLUMN FPF_FILE.FILE_NAME IS '文件名称';
COMMENT ON COLUMN FPF_FILE.FILE_CODE IS '文件编码';
COMMENT ON COLUMN FPF_FILE.FILE_DESC IS '文件描述';
COMMENT ON COLUMN FPF_FILE.STATUS IS '状态';--待审核，审核通过，审核不通过，已删除
COMMENT ON COLUMN FPF_FILE.FILE_PATH IS '文件路径';
COMMENT ON COLUMN FPF_FILE.CREATOR_ID IS '创建者ID';
COMMENT ON COLUMN FPF_FILE.CREATOR IS '创建者';
COMMENT ON COLUMN FPF_FILE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN FPF_FILE.APPROVER_ID IS '审核人ID';
COMMENT ON COLUMN FPF_FILE.APPROVER IS '审核人';
COMMENT ON COLUMN FPF_FILE.APPROVE_TIME IS '审核时间';
COMMENT ON COLUMN FPF_FILE.APPROVE_OPINION IS '审核意见';
COMMENT ON COLUMN FPF_FILE.REQ_ID IS '相关需求ID';
    
CREATE TABLE
"ST".FPF_FILE_LOG
(
    ID VARCHAR(32) NOT NULL,
    FILE_ID VARCHAR(32) NOT NULL,
    USER_ID VARCHAR(32) NOT NULL,
    USER_NAME VARCHAR(32) NOT NULL,
    OPER_TYPE VARCHAR(32) NOT NULL,
    OPER_TIME TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);
COMMENT ON TABLE FPF_FILE_LOG IS '文件日志表';
COMMENT ON COLUMN FPF_FILE_LOG.ID IS 'ID';
COMMENT ON COLUMN FPF_FILE_LOG.FILE_ID IS '文件ID';
COMMENT ON COLUMN FPF_FILE_LOG.USER_ID IS '用户ID';
COMMENT ON COLUMN FPF_FILE_LOG.USER_NAME IS '用户名';
COMMENT ON COLUMN FPF_FILE_LOG.OPER_TYPE IS '操作类型';--上传，删除，审核，下载
COMMENT ON COLUMN FPF_FILE_LOG.OPER_TIME IS '操作时间';