/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2017-08-02 09:37:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.hbbass.salesmanager.areasale.bureauAudit;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.asiainfo.hbbass.common.jdbc.ConnectionManage;
import java.sql.*;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;

public final class bureau_005fnewdel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String userid = (String)session.getAttribute("loginname");
Connection conn = null;
String region = null;
String cityName="";
boolean isProvince = false;
String provinceOperatorCN = null;
String operatorCN = null;
boolean hasRight = false;
boolean _aduitFlag = true ;
Date currentDate = new Date();
		String formatString = "yyyy-MM-dd";
		SimpleDateFormat df = new SimpleDateFormat(formatString);
		String defaultDate =  df.format(currentDate);
try{
	conn = ConnectionManage.getInstance().getWEBConnection();
	
	String sql = "select cityid from FPF_USER_USER where userid='"+userid+"'";
	PreparedStatement ps = conn.prepareStatement(sql);
	ResultSet rs = ps.executeQuery();
	String cityid = null;
	if(rs.next()){
		cityid = rs.getString(1);
		System.out.println("用户的cityid："+cityid);
	}
	
	//如果cityid == 0 ，则是省公司用户，否则为地市用户
	if("0".equals(cityid)){
		isProvince = true;
	}else{
		isProvince = false;
	}
	
	//求出省公司用户该谁审批
	sql = "select OPERATOR,b.username from FPF_AUDIT_FLOW a,FPF_USER_USER b  where a.cityid = '0' and a.operator = b.userid";
	ps = conn.prepareStatement(sql);
	rs = ps.executeQuery();
	String provinceOperator = null;
	provinceOperatorCN = null;
	if(rs.next()){
		provinceOperator = rs.getString(1);
		provinceOperatorCN = rs.getString(2);
		System.out.println("省公司用户该谁审批："+provinceOperatorCN);
		if(userid.equals(provinceOperator)){
			hasRight = true;
		}
	}
	
	//求出地市用户该谁审批
	//sql = "select OPERATOR,b.username,OPERATOR2,(SELECT C.USERNAME FORM FPF_USER_USER C WHERE A.OPERATOR2=C.USERID ) from FPF_AUDIT_FLOW a,FPF_USER_USER b  where a.cityid = '"+cityid+"' and a.operator = b.userid";
	sql = "select OPERATOR,b.username,OPERATOR2,c.username op2username from FPF_AUDIT_FLOW a,FPF_USER_USER b,FPF_USER_USER c  where a.cityid = '"+cityid+"' and a.operator = b.userid and a.operator2 = c.userid" ;
	ps = conn.prepareStatement(sql);
	rs = ps.executeQuery();
	String operator = null;
	operatorCN = null;
	
	if(rs.next()){
		operator = rs.getString(1);
		operatorCN = rs.getString(2);
		System.out.println("此地区由谁审批："+operatorCN);
		if(userid.equals(operator)){
			hasRight = true;
			provinceOperatorCN = rs.getString("op2username");
			provinceOperator = rs.getString("OPERATOR2");
		}
		if (userid.equalsIgnoreCase(rs.getString("OPERATOR2"))){
		   hasRight = true;
		    operator = rs.getString("OPERATOR2");
		    operatorCN = rs.getString("op2username");
		    _aduitFlag = false ;
		}
	}
	
	
	//求出该用户的areaid
	sql = "select b.region,b.itemname from FPF_USER_USER a,mk.dim_areacity b where char(a.cityid) = char(b.site_id) and userid='"+userid+"'";
	ps = conn.prepareStatement(sql);
	rs = ps.executeQuery();
	if(rs.next()){
		region = rs.getString(1);
		cityName = rs.getString(2);
		System.out.println("该用户的区域："+region);
	}

	if(isProvince){
		System.out.println("省审批流程为："+provinceOperator);
	}else{
		if (_aduitFlag == true){
		  System.out.println("地市一级审批流程为："+operatorCN +"-->"+provinceOperatorCN);
		}else{
		  System.out.println("地市二级审批流程为："+operatorCN +"-->"+provinceOperatorCN);
		}
	}
	
	rs.close();
	ps.close();
}catch ( SQLException e){
	e.printStackTrace();
}finally{
	if(conn!=null)
		conn.close();
}

      out.write("\t\r\n");
      out.write("<html xmlns:ai>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\">\r\n");
      out.write("\t\t<title>基站新增、删除审核</title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/js/ext/resources/css/ext-all.css\"/>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/js/ext/resources/css/xtheme-slate.css\" />\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/js/ext/ext-base.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/js/ext/ext-all.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/js/default/default.js\" charset=utf-8></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/js/default/tabext.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/js/default/calendar.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hb-bass-primary/js/default/des.js\" charset=utf-8></script>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/css/default/default.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/js/ext/resources/css/ext-all.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/js/ext/resources/css/xtheme-gray.css\" />\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/js/datepicker/WdatePicker.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("var _header=[\r\n");
      out.write("\t{\"name\":\"选择\",\"dataIndex\":\"c0\",cellFunc:\"setId\",cellStyle:\"grid_row_cell\"}\r\n");
      out.write("\t,{\"name\":\"流水号\",\"dataIndex\":\"c1\"}\r\n");
      out.write("\t,{\"name\":\"地市码\",\"dataIndex\":\"c2_1\"}\r\n");
      out.write("\t,{\"name\":\"地市\",\"dataIndex\":\"c2\"}\r\n");
      out.write("\t,{\"name\":\"区域营销中心\",\"dataIndex\":\"c21\"}\r\n");
      out.write("\t,{\"name\":\"区域营销中心代码\",\"dataIndex\":\"c31\"}\r\n");
      out.write("\t//,{\"name\":\"镇\",\"dataIndex\":\"c22\"}\r\n");
      out.write("\t//,{\"name\":\"基站\",\"dataIndex\":\"c23\"}\r\n");
      out.write("\t,{\"name\":\"县/营业部编码\",\"dataIndex\":\"c6_1_1\"}\r\n");
      out.write("\t,{\"name\":\"县/营业部名称\",\"dataIndex\":\"c6_1_2\"}\r\n");
      out.write("\t,{\"name\":\"营销中心编码\",\"dataIndex\":\"c6_1_3\"}\r\n");
      out.write("\t,{\"name\":\"营销中心名称\",\"dataIndex\":\"c6_1_4\"}\r\n");
      out.write("\t,{\"name\":\"乡镇/街道名\",\"dataIndex\":\"c6_1\"}\r\n");
      out.write("\t,{\"name\":\"乡镇/街道唯一码\",\"dataIndex\":\"c6\"}\r\n");
      out.write("\t,{\"name\":\"lac码\",\"dataIndex\":\"c3\"}\r\n");
      out.write("\t,{\"name\":\"cell码\",\"dataIndex\":\"c4\"}\r\n");
      out.write("\t,{\"name\":\"基站码\",\"dataIndex\":\"c5\"}\r\n");
      out.write("\t,{\"name\":\"基站名称\",\"dataIndex\":\"c5_1\"}\r\n");
      out.write("\t,{\"name\":\"导入人员\",\"dataIndex\":\"c7\"}\r\n");
      out.write("\t,{\"name\":\"创建时间\",\"dataIndex\":\"c8\"}\r\n");
      out.write("\t//,{\"name\":\"是否为高校\",\"dataIndex\":\"c0_1\",cellFunc:\"setUniversity\",cellStyle:\"grid_row_cell\"}\r\n");
      out.write("\t,{\"name\":\"归属高校名称\",\"dataIndex\":\"c12_1\",cellFunc:\"setNullValue\",cellStyle:\"grid_row_cell\"}\r\n");
      out.write("\t,{\"name\":\"操作类型\",\"dataIndex\":\"c9\"}\r\n");
      out.write("\t,{\"name\":\"状态\",\"dataIndex\":\"c10\"}\t\t\r\n");
      out.write("\t,{\"name\":\"状态时间\",\"dataIndex\":\"c11\"}\r\n");
      out.write("\t//,{\"name\":\"生效类型\",\"dataIndex\":\"c12\"}\r\n");
      out.write("];\r\n");
      out.write("var _select_id ='';\r\n");
      out.write("function getwhere(datefield){\r\n");
      out.write("var s = $('sdate1').value;\r\n");
      out.write("var d = $('sdate2').value;\r\n");
      out.write("  if (s == d){\r\n");
      out.write("     return '';\r\n");
      out.write("  }else{\r\n");
      out.write("  \t return ' and ' +datefield +'>=timestamp(\\''+ s + ' 00:00:00\\') and ' +datefield +'<=timestamp(\\'' + d + ' 23:59:59\\') ';\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("function getwhereDate(datefield,obj1,obj2){\r\n");
      out.write("\tvar s = $(obj1).value;\r\n");
      out.write("\tvar d = $(obj2).value;\r\n");
      out.write("\t  if (s == d){\r\n");
      out.write("\t     return '';\r\n");
      out.write("\t  }else{\r\n");
      out.write("\t  \t return ' and ' +datefield +'>=timestamp(\\''+ s + ' 00:00:00\\') and ' +datefield +'<=timestamp(\\'' + d + ' 23:59:59\\') ';\r\n");
      out.write("\t  }\r\n");
      out.write("}\r\n");
      out.write("function selcetUniversity(strID){\r\n");
      out.write("    //alert(strID);\r\n");
      out.write("    var n = document.getElementsByName('cbox').length;\r\n");
      out.write("    for (var i=0;i<n;i++){\r\n");
      out.write("            if (document.getElementsByName('cbox')[i].value == strID ){\r\n");
      out.write("                document.getElementsByName('cbox')[i].checked = true ;\r\n");
      out.write("                break ;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    \r\n");
      out.write("    if (document.getElementsByName('U_'+strID)[0].checked){\r\n");
      out.write("         if(_select_id == \"\"){\r\n");
      out.write("\t\t\t\t\t_select_id += strID;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t_select_id += \",\" + strID;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("    }else{\r\n");
      out.write("        _select_id = _select_id.replace(','+strID,'');\r\n");
      out.write("        _select_id = _select_id.replace(strID,'');\r\n");
      out.write("    }\r\n");
      out.write("   // alert(_select_id);\r\n");
      out.write("}\r\n");
      out.write("function setUniversity(dataIndex,options){\r\n");
      out.write("\tvar str = \"U_\" + options.data[options.rowIndex].c1 ;\r\n");
      out.write("\t//return \"<input type='checkbox' name='cbox' value=\\\"\"+str+\"\\\">\";\r\n");
      out.write("\t\r\n");
      out.write("\t//var _ipt=$C(\"input\");\r\n");
      out.write("\t//_ipt.type=\"radio\";\r\n");
      out.write("\t//_ipt.name= \"'\"+str+\"'\";\r\n");
      out.write("\t//_ipt.id = \"'\"+str+\"'\";\r\n");
      out.write("\t//_ipt.value=\"'YES'\";\r\n");
      out.write("\tvar _ipt = \"<input type='radio' id='\"+str+\"' name='\"+str+\"' onclick=\\\"selcetUniversity('\"+options.data[options.rowIndex].c1+\"')\\\" value='是'>是</input>\";\r\n");
      out.write("\t_ipt +=(\"<input type='radio' id='\"+str+\"' onclick=\\\"selcetUniversity('\"+options.data[options.rowIndex].c1+\"')\\\" name='\"+str+\"' value='否' checked  >否</input>\");\r\n");
      out.write("\tif (options.data[options.rowIndex].c9=='删除'){\r\n");
      out.write("\t   return '';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\treturn _ipt;\r\n");
      out.write("}\r\n");
      out.write("function setNullValue(dataIndex,options){\r\n");
      out.write("\tvar str = options.data[options.rowIndex].c12_1;\r\n");
      out.write("\tif (str == null)\r\n");
      out.write("\t   str = '';\r\n");
      out.write("\treturn str;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function setId(dataIndex,options){\r\n");
      out.write("\tvar str = options.data[options.rowIndex].c1;\r\n");
      out.write("\treturn \"<input type='checkbox' name='cbox' value=\\\"\"+str+\"\\\">\";\r\n");
      out.write("\t\r\n");
      out.write("\t//var _ipt=$C(\"input\");\r\n");
      out.write("\t//_ipt.type=\"checkbox\";\r\n");
      out.write("\t//_ipt.name=\"cbox\";\r\n");
      out.write("\t//_ipt.value=str;\r\n");
      out.write("\t\r\n");
      out.write("\t//_ipt.onclick=function(){\r\n");
      out.write("\t//\tvar record = options.record;\r\n");
      out.write("\t\t\r\n");
      out.write("\t//}\r\n");
      out.write("\t\r\n");
      out.write("\t//return _ipt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function genSQL(){\r\n");
      out.write("\tvar selType = $('selType').value;\r\n");
      out.write("\t\r\n");
      out.write("\tvar num = Math.random();\r\n");
      out.write("\t\r\n");
      out.write("\tif(\"toDo\" == selType){\r\n");
      out.write("\t\tvar wherePiece = \" where 1=1 \";\r\n");
      out.write("\t\tif($('OPERATE_TYPE').value != null && $('OPERATE_TYPE').value != \"\"){\r\n");
      out.write("\t\t\twherePiece += \" and OPERATE_TYPE='\"+$('OPERATE_TYPE').value+\"'\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t");

		if(isProvince){//省
		
      out.write("\r\n");
      out.write("\t\t\twherePiece += \" and (STATUS='waitaudit3') \";\r\n");
      out.write("\t\t\tif($('areaSel').value != 0){\r\n");
      out.write("\t\t\t\twherePiece += \" and area_id = '\"+$('areaSel').value+\"' \";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t");
	
		}else{//地市
		
		  if (_aduitFlag == true){
		
      out.write("\r\n");
      out.write("\t\t\twherePiece += \" and (STATUS='waitaudit1') \";\r\n");
      out.write("\t\t\twherePiece += \" and area_id = '");
      out.print(region);
      out.write("' \";\r\n");
      out.write("\t\t");

		}else {
		
      out.write("\r\n");
      out.write("\t\t\twherePiece += \" and (STATUS='waitaudit2') \";\r\n");
      out.write("\t\t\twherePiece += \" and area_id = '");
      out.print(region);
      out.write("' \";\r\n");
      out.write("\t\t");

		}
		}
		
      out.write("\r\n");
      out.write("\t\t");

		if(hasRight){//当前用户为审批人
		
      out.write("\r\n");
      out.write("\t\t");
	
		}else{//当前用户不是审批人
		
      out.write("\r\n");
      out.write("\t\t\t//wherePiece += \" and 1=2\";\r\n");
      out.write("\t\t\twherePiece += \" and 1=2\";\r\n");
      out.write("\t\t");

		}
		
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//var sql=\"select '' c0,'' c0_1,newdelcell_seq c1,area_id c2_1,(select dim.itemname from mk.dim_areacity dim where char(dim.region)=area_id) c2,LAC_DEC c3,CELLID_DEC c4,Bureau_ID c5,bureau_name c5_1,(select A.name from nwh.bureau_tree A where A.ID=town_code) c6_1,(select B.county_code  from nwh.vdim_bureau_tree B where B.town_code=F.town_code) c6_1_1,(select B.COUNTY_NAME  from nwh.vdim_bureau_tree B where B.town_code=F.town_code) c6_1_2,(select B.ZONE_CODE  from nwh.vdim_bureau_tree B where B.town_code=F.town_code) c6_1_3,(select B.ZONE_NAME  from nwh.vdim_bureau_tree B where B.town_code=F.town_code) c6_1_4,town_code c6,createuser c7,substr(char(CREATE_DATE),1,19) c8,case when operate_type='new' then '新增' when operate_type='del' then '删除' end c9,case when STATUS='waitaudit1' then '待一级审核' when STATUS='waitaudit2' then '待二级审核' when STATUS='waitaudit3' then '待三级审核' when STATUS='succ' then '审核通过'  when STATUS='fail' then '审核不通过'  end c10,substr(char(STATE_DATE),1,19) c11,case when eff_type='0' then '立即生效' when eff_type='1' then '下月生效' end c12 from BUREAU_CELL_NEWDEL_INFO F \"\r\n");
      out.write("\t\tvar sql=\"select '' c0,'' c0_1,newdelcell_seq c1,area_id c2_1,(select dim.itemname from mk.dim_areacity dim where char(dim.region)=area_id) c2,LAC_DEC c3,CELLID_DEC c4,Bureau_ID c5,bureau_name c5_1,(select A.name from nwh.bureau_tree A where A.ID=town_code) c6_1,(select B.county_code  from nwh.vdim_bureau_tree B where B.town_code=F.town_code) c6_1_1,(select B.COUNTY_NAME  from nwh.vdim_bureau_tree B where B.town_code=F.town_code) c6_1_2,(select B.ZONE_CODE  from nwh.vdim_bureau_tree B where B.town_code=F.town_code) c6_1_3,(select B.zone_name  from nwh.vdim_bureau_tree B where B.town_code=F.town_code) c6_1_4,town_code c6,createuser c7,substr(char(CREATE_DATE),1,19) c8,case when operate_type='new' then '新增' when operate_type='del' then '删除' end c9,case when STATUS='waitaudit1' then '待一级审核' when STATUS='waitaudit2' then '待二级审核' when STATUS='waitaudit3' then '待三级审核' when STATUS='succ' then '审核通过'  when STATUS='fail' then '审核不通过'  end c10,substr(char(STATE_DATE),1,19) c11,case when eff_type='0' then '立即生效' when eff_type='1' then '下月生效' end c12,(select A.college_name from BUREAU_COLLEGE_ORINFO A where A.newdelcell_seq=F.newdelcell_seq  and A.state_time = (select max(B.state_time) from BUREAU_COLLEGE_ORINFO B where B.newdelcell_seq=F.newdelcell_seq)) C12_1 from BUREAU_CELL_NEWDEL_INFO F \"\r\n");
      out.write("\t\t\t+ wherePiece\r\n");
      out.write("\t\t  + getwhere('STATE_DATE')\r\n");
      out.write("\t\t  + getwhereDate('CREATE_DATE','date3','date4')\t\r\n");
      out.write("\t\t\t+ \" order by c6_1,c6_1_4,c6_1_2 \"\r\n");
      out.write("\t\t\t+\" with ur\";\r\n");
      out.write("\t\treturn sql;\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tif(\"hasDone\" == selType){\r\n");
      out.write("\t\tvar wherePiece = \" and 1=1 \";\r\n");
      out.write("\t\tif($('OPERATE_TYPE').value != null && $('OPERATE_TYPE').value != \"\"){\r\n");
      out.write("\t\t\twherePiece += \" and a.OPERATE_TYPE='\"+$('OPERATE_TYPE').value+\"'\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($('STATUS').value != null && $('STATUS').value != \"\"){\r\n");
      out.write("\t\t\twherePiece += \" and a.STATUS='\"+$('STATUS').value+\"'\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t");

		if(isProvince){//省
		
      out.write("\r\n");
      out.write("\t\t\tif($('areaSel').value != 0){\r\n");
      out.write("\t\t\t\twherePiece += \" and a.area_id = '\"+$('areaSel').value+\"' \";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t");
	
		}
		
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar sql=\"select '' c0,'' c0_1,a.newdelcell_seq c1,area_id c2_1,(select dim.itemname from mk.dim_areacity dim where char(dim.region)=area_id) c2,LAC_DEC c3,CELLID_DEC c4,Bureau_ID c5,(select A.name from nwh.bureau_tree A where A.ID=town_code) c6_1,town_code c6,createuser c7,substr(char(CREATE_DATE),1,19) c8,case when a.operate_type='new' then '新增' when a.operate_type='del' then '删除' end c9,case when a.STATUS='waitaudit1' then '待一级审核' when a.STATUS='waitaudit2' then '待二级审核' when a.STATUS='waitaudit3' then '待三级审核' when a.STATUS='succ' then '审核通过'  when a.STATUS='fail' then '审核不通过'  end c10,substr(char(a.STATE_DATE),1,19) c11,case when eff_type='0' then '立即生效' when eff_type='1' then '下月生效' end c12 from BUREAU_CELL_NEWDEL_INFO a,BUREAU_CELL_NEWDEL_AUDIT_LOG b where a.NEWDELCELL_SEQ = b.NEWDELCELL_SEQ and b.OPERATOR = '");
      out.print(userid);
      out.write("' \"\r\n");
      out.write("\t\t\t+ wherePiece\r\n");
      out.write("\t\t\t+ getwhere('STATE_DATE')\r\n");
      out.write("\t\t\t+ getwhereDate('CREATE_DATE','date3','date4')\t\r\n");
      out.write("\t\t\t+ \" order by c2\"\r\n");
      out.write("\t\t\t+\" with ur\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\treturn sql;\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tif(\"allRec\" == selType){\r\n");
      out.write("\t\tvar wherePiece = \" where 1=1 \";\r\n");
      out.write("\t\tif($('OPERATE_TYPE').value != null && $('OPERATE_TYPE').value != \"\"){\r\n");
      out.write("\t\t\twherePiece += \" and OPERATE_TYPE='\"+$('OPERATE_TYPE').value+\"'\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($('STATUS').value != null && $('STATUS').value != \"\"){\r\n");
      out.write("\t\t\twherePiece += \" and STATUS='\"+$('STATUS').value+\"'\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t");

		if(isProvince){//省
			
      out.write("\r\n");
      out.write("\t\t\tif($('areaSel').value != 0){\r\n");
      out.write("\t\t\t\twherePiece += \" and area_id = '\"+$('areaSel').value+\"' \";\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t\t");
	
		}else{//地市
		
      out.write("\r\n");
      out.write("\t\t\twherePiece += \" and area_id = '");
      out.print(region);
      out.write("' \";\r\n");
      out.write("\t\t");

		}
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar sql=\"select '' c0,'' c0_1,newdelcell_seq c1,area_id c2_1,(select dim.itemname from mk.dim_areacity dim where char(dim.region)=area_id) c2,LAC_DEC c3,CELLID_DEC c4,Bureau_ID c5,bureau_name c5_1,(select A.name from nwh.bureau_tree A where A.ID=town_code) c6_1,town_code c6,createuser c7,substr(char(CREATE_DATE),1,19) c8,case when operate_type='new' then '新增' when operate_type='del' then '删除' end c9,case when STATUS='waitaudit1' then '待一级审核' when STATUS='waitaudit2' then '待二级审核' when STATUS='succ' then '审核通过'  when STATUS='fail' then '审核不通过'  end c10,substr(char(STATE_DATE),1,19) c11,case when eff_type='0' then '立即生效' when eff_type='1' then '下月生效' end c12 ,zone_name c21,zone_code c31,town_name c22,cell_name c23 from (select a.* ,b.zone_name,zone_code,town_name,bureau_name cell_name from BUREAU_CELL_NEWDEL_INFO a left join nwh.vdim_bureau_tree b on a.town_code=b.town_code) tt \"\r\n");
      out.write("\t\t\t+ wherePiece\r\n");
      out.write("\t\t\t+ getwhere('STATE_DATE')\r\n");
      out.write("\t\t\t+ getwhereDate('CREATE_DATE','date3','date4')\t\r\n");
      out.write("\t\t\t+ \" order by c2,c21,c22,c23\"\r\n");
      out.write("\t\t\t+\" with ur\";\r\n");
      out.write("\t\t//alert(sql);\t\r\n");
      out.write("\t\treturn sql;\t\r\n");
      out.write("\t}\t\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function query(){\r\n");
      out.write("\tvar grid = new aihb.AjaxGrid({\r\n");
      out.write("\t\theader:_header\r\n");
      out.write("\t\t,sql: genSQL()\r\n");
      out.write("\t\t,isCached : false\r\n");
      out.write("\t\t,limit:400\r\n");
      out.write("\t\t,pageSize : 200\r\n");
      out.write("\t});\r\n");
      out.write("\tgrid.run();\r\n");
      out.write("\t/*aihb.AjaxHelper.request({\r\n");
      out.write("\t\theader:_header\r\n");
      out.write("\t\t,url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbirs/action/jsondata?sql=\"+sql\r\n");
      out.write("\t});*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//function down(){\r\n");
      out.write("//\tvar _fileName=document.title;\r\n");
      out.write("//\taihb.AjaxHelper.down({url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbirs/action/jsondata?method=down&sql=\"+strEncode(genSQL())+\"&fileName=\"+_fileName});\r\n");
      out.write("//}\r\n");
      out.write("\r\n");
      out.write("\tfunction down(){\r\n");
      out.write("\t\taihb.AjaxHelper.down({\r\n");
      out.write("\t\t\tsql : genSQL()\r\n");
      out.write("\t\t\t,header : _header\r\n");
      out.write("\t\t\t,ds:\"dw\"\r\n");
      out.write("\t\t\t,isCached : false\r\n");
      out.write("\t\t\t,\"url\" : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbirs/action/jsondata?method=down&fileKind=excel\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("aihb.Util.loadmask();\r\n");
      out.write("window.onload=function(){\r\n");
      out.write("\tvar _d=new Date();\r\n");
      out.write("\t_d.setDate(_d.getDate()-1);\r\n");
      out.write("\t\r\n");
      out.write("\tvar _headerStr=\"\";\r\n");
      out.write("\t\r\n");
      out.write("\tfor(var i=0;i<_header.length;i++){\r\n");
      out.write("\t\tvar header=_header[i];\r\n");
      out.write("\t\tif(_headerStr.length>0){\r\n");
      out.write("\t\t\t_headerStr+=\",\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t_headerStr+=\"\\\"\"+header.dataIndex.toLowerCase()+\"\\\":\\\"\"+header.name+\"\\\"\";\r\n");
      out.write("\t}\r\n");
      out.write("\t_headerStr=\"{\"+_headerStr+\"}\";\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.forms[0].header.value=_headerStr;\r\n");
      out.write("\t\r\n");
      out.write("\tquery();\r\n");
      out.write("\t\r\n");
      out.write("};\r\n");
      out.write("</script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t.dim_cell_title_wide {\r\n");
      out.write("\t\tfont-family: \"宋体\";\r\n");
      out.write("\t\tfont-size: 12px;\r\n");
      out.write("\t\tline-height: 20px;\r\n");
      out.write("\t\tfont-weight: normal;\r\n");
      out.write("\t\tfont-variant: normal;\r\n");
      out.write("\t\tcolor: #000000;\r\n");
      out.write("\t\twidth: 20%;\r\n");
      out.write("\t\tbackground-color: #D9ECF6;\r\n");
      out.write("\t}\t\r\n");
      out.write("\t</style>\t\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<form method=\"post\" action=\"\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"header\">\r\n");
      out.write("\t\t\t<div class=\"divinnerfieldset\">\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t<legend>\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td onclick=\"hideTitle(this.childNodes[0],'dim_div')\" title=\"点击隐藏\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img flag='1' src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/image/default/ns-expand.gif\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;查询条件区域：\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</legend>\r\n");
      out.write("\t\t\t\t\t<div id=\"dim_div\">\r\n");
      out.write("\t\t\t\t\t\t<table align='center' width='99%' class='grid-tab-blue' cellspacing='1' cellpadding='0' border='0'>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class='dim_row'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='dim_cell_title' id=\"times_start\" >状态时间:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='dim_cell_content' > \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" value='");
      out.print(defaultDate);
      out.write("' id=\"sdate1\" onfocus=\"WdatePicker({readOnly:true,dateFmt:'yyyy-MM-dd'})\" class=\"Wdate\" size=\"12\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t至\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" value='");
      out.print(defaultDate);
      out.write("' id=\"sdate2\" onfocus=\"WdatePicker({readOnly:true,dateFmt:'yyyy-MM-dd'})\" class=\"Wdate\" size=\"12\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='dim_cell_title' id=\"times_end\" >创建时间:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='dim_cell_content' > \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" value='");
      out.print(defaultDate);
      out.write("' id=\"date3\" onfocus=\"WdatePicker({readOnly:true,dateFmt:'yyyy-MM-dd'})\" class=\"Wdate\" size=\"12\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t至\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" value='");
      out.print(defaultDate);
      out.write("' id=\"date4\" onfocus=\"WdatePicker({readOnly:true,dateFmt:'yyyy-MM-dd'})\" class=\"Wdate\" size=\"12\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='dim_cell_title'></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='dim_cell_content'></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class='dim_row'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='dim_cell_title'>操作类型</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='dim_cell_content'><select id=\"OPERATE_TYPE\"><option value=\"\">全部</option><option value=\"new\">新增</option><option value=\"del\">删除</option></select></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='dim_cell_title' id=\"area_td1\">地市</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='dim_cell_content' id=\"area_td2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"areaSel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								if(isProvince){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='0' selected='selected'>全省</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='270'>武汉</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='714'>黄石</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='711'>鄂州</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='717'>宜昌</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='718'>恩施</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='719'>十堰</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='710'>襄樊</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='728'>江汉</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='715'>咸宁</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='716'>荆州</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='724'>荆门</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='722'>随州</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='713'>黄冈</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='712'>孝感</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='728'>天门</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='728'>潜江</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

								}else{
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>");
      out.print(cityName );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

								}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='dim_cell_title' id=\"status_td1\">状态</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='dim_cell_content' id=\"status_td2\"><select id=\"STATUS\" disabled=\"disabled\"><option value=\"\">全部</option><option value=\"waitaudit1\">待一级审核</option><option value=\"waitaudit2\">待二级审核</option><option value=\"waitaudit3\">待三级审核</option><option value=\"succ\">审核通过</option><option value=\"fail\">审核不通过</option></select></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr id=\"eff\" style=\"display: none\"><!-- 默认全为立即生效 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='dim_cell_title_wide' id=\"eff_td1\">审批生效类型(非查询条件，仅供审批使用)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='dim_cell_content' id=\"eff_td2\" colspan=\"5\"><select id=\"eff_type\"><option value=\"\">不更改</option><option value=\"0\" selected=\"selected\">立即生效</option><option value=\"1\">下月生效</option></select></td>\t\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<table align=\"center\" width=\"99%\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"dim_row_submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"form_button\" value=\"查询\" onClick=\"query()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"form_button\" value=\"下载\" onclick=\"down()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"form_button\" value=\"查看日志\" onClick=\"viewDetail()\" id=\"viewDetaibtn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									if(hasRight){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"form_button\" value=\"审批通过\" onClick=\"pass()\" id=\"passbtn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"form_button\" value=\"审批不通过\" onClick=\"fail()\" id=\"failbtn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
	
									}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div class=\"divinnerfieldset\">\r\n");
      out.write("\t\t\t<table><tr><td>本地区的审批流程：\r\n");
      out.write("\t\t\t");
			
			if(isProvince){
				
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.print( provinceOperatorCN);
      out.write("\r\n");
      out.write("\t\t\t\t");

			}else{
				
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.print( operatorCN);
      out.write(" --> ");
      out.print( provinceOperatorCN);
      out.write("\r\n");
      out.write("\t\t\t\t");

			}
			
      out.write("\r\n");
      out.write("\t\t\t</td></tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t<legend>\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td onclick=\"hideTitle(this.childNodes[0],'show_div')\" title=\"点击隐藏\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img flag='1' src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/image/default/ns-expand.gif\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;数据展现区域：\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>全选<input type=\"checkbox\" name=\"checkAllBox\" onclick=\"selAll();\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</legend>\r\n");
      out.write("\t\t    \t\t<table style=\"border-collapse:collapse;border-color:#9AADBE;BACKGROUND-COLOR:#ffffff;border-top:0px;border-bottom:0px;margin-left: 6px\" border=1>\r\n");
      out.write("\t\t\t\t\t<tr height=\"21px\" valign=\"top\" style=\"padding-bottom:0px;padding-top:3px;WIDTH: 10%; border-collapse:collapse;border-color:#9AADBE;BACKGROUND-COLOR:81A3F5\">\r\n");
      out.write("\t\t\t\t\t\t<td  class=\"tab\" background=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/image/default/tab1.png onclick='changetab(\"toDo\");'>&nbsp;待我审核</TD>\r\n");
      out.write("\t\t\t\t\t\t<td  class=\"tab\" background=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/image/default/tab2.png onclick='changetab(\"hasDone\");'>我已审核</TD>\r\n");
      out.write("\t\t\t\t\t\t<td  class=\"tab\" background=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/image/default/tab2.png onclick='changetab(\"allRec\");'>全部记录</TD>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" id=\"selType\" value=\"toDo\">\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"grid\" style=\"display: none;\"></div>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("        Ext.onReady(function(){\r\n");
      out.write("\t  \tExt.QuickTips.init();\r\n");
      out.write("\t  \tExt.BLANK_IMAGE_URL = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/js/ext/resources/images/default/s.gif';\r\n");
      out.write("      Ext.form.Field.prototype.msgTarget = 'side';\r\n");
      out.write("      contextPath = window.location['pathname'].split('/')[1];\r\n");
      out.write("          \r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getGridPanel(){\r\n");
      out.write("\r\n");
      out.write("     if (_select_id.trim() != ''){\r\n");
      out.write("          var strNewId = _select_id.trim().split(\",\");\r\n");
      out.write("          //alert('长度:'+strNewId.length);\r\n");
      out.write("          var selectd = \"\";\r\n");
      out.write("          for (var i=0;i<strNewId.length;i++){\r\n");
      out.write("              if(selectd == \"\"){\r\n");
      out.write("\t\t\t\t\tselectd += strNewId[i];\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tselectd += \",\" + strNewId[i];\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("          }\r\n");
      out.write("         //alert(selectd);\r\n");
      out.write("         var _Uselect = \"select A.NEWDELCELL_SEQ,A.bureau_name,A.BUREAU_ID,B.COLLEGE_ID,COLLEGE_NAME,B.OPERATOR,(select C.county_code  from nwh.vdim_bureau_tree C where C.town_code=A.town_code) county_code,(select C.COUNTY_NAME  from nwh.vdim_bureau_tree C where C.town_code=A.town_code) COUNTY_NAME,(select C.ZONE_CODE  from nwh.vdim_bureau_tree C where C.town_code=A.town_code) ZONE_CODE,(select C.ZONE_NAME  from nwh.vdim_bureau_tree C where C.town_code=A.town_code) ZONE_NAME from (select * from BUREAU_CELL_NEWDEL_INFO  where NEWDELCELL_SEQ IN (\"+selectd+\")) A left join (select * from BUREAU_COLLEGE_ORINFO  C where state_time= (select MAX(state_time) from BUREAU_COLLEGE_ORINFO D WHERE C.NEWDELCELL_SEQ= D.NEWDELCELL_SEQ) ) B on A.NEWDELCELL_SEQ=B.NEWDELCELL_SEQ\";\r\n");
      out.write("             var ds=new Ext.data.Store({\r\n");
      out.write("                    proxy: new Ext.data.HttpProxy({url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbirs/action/jsondata?method=query&sql=\"+_Uselect+\"&isCached=false&qType=limit&start=1&limit=510\"}),\r\n");
      out.write("                    reader: new Ext.data.JsonReader({\r\n");
      out.write("                        root: 'data',\r\n");
      out.write("                        totalProperty:'total'\r\n");
      out.write("                   },[ 'newdelcell_seq','bureau_name','bureau_id','college_id','college_name','operator','county_code','county_name','zone_code','zone_name']\r\n");
      out.write("            ) \r\n");
      out.write("    });\r\n");
      out.write("    ds.load({\r\n");
      out.write("   params : {//这两个参数是分页的关键，当你点击 下一页 时，这里的值会传到后台,也就是会重新运行：store.load\r\n");
      out.write("    start : 0,   \r\n");
      out.write("    limit : 30\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("   var _Uselect = \"select distinct college_id id,college_name value from NWH.COLLEGE_INFO where state=1 and area_id in (select itemid from mk.dim_areacity where  region=");
      out.print(region);
      out.write(") order by college_name asc \";\r\n");
      out.write("             var ds_1=new Ext.data.Store({\r\n");
      out.write("                    proxy: new Ext.data.HttpProxy({url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbirs/action/jsondata?method=query&sql=\"+_Uselect+\"&qType=limit&start=1&limit=510\"}),\r\n");
      out.write("                    reader: new Ext.data.JsonReader({\r\n");
      out.write("                        root: 'data',\r\n");
      out.write("                        totalProperty:'total'\r\n");
      out.write("                   },[ 'id','value']\r\n");
      out.write("            ) \r\n");
      out.write("    });\r\n");
      out.write("    ds_1.load();\r\n");
      out.write("    \r\n");
      out.write("    var fd_University_edit = new Ext.form.ComboBox({\r\n");
      out.write("\t  fieldLabel:'fd_University_edit',\r\n");
      out.write("\t  id:'fd_University_edit',\r\n");
      out.write("\t  mode: 'remote',\r\n");
      out.write("      triggerAction:'all',\r\n");
      out.write("      store:ds_1,\r\n");
      out.write("      ds:ds,\r\n");
      out.write("      editable: false,\r\n");
      out.write("      blankText:'请选择...',\r\n");
      out.write("      \tvalueField: 'id',displayField: 'value',\r\n");
      out.write("      \tforceSelection: true,\r\n");
      out.write("      allowBlank:false//,\r\n");
      out.write("//      listeners:{\r\n");
      out.write("//         select:{\r\n");
      out.write("//            fn:function(combo,record,index){\r\n");
      out.write("//               alert(record.get('id'));\r\n");
      out.write("//               alert(index);\r\n");
      out.write("//               combo.get1();\r\n");
      out.write("               // alert(fd_University_edit.lastSelectionText);\r\n");
      out.write("                //Ext.get(\"'UName_\"+record.get('newdelcell_seq')+\"'\").setValue=fd_University_edit.lastSelectionText ;\r\n");
      out.write("//            }\r\n");
      out.write("//         }\r\n");
      out.write("//      }\r\n");
      out.write(" }); \r\n");
      out.write("    fd_University_edit.on('select',function(){\r\n");
      out.write("         //alert(fd_University_edit.lastSelectionText);\r\n");
      out.write("        //var record = ds.data;\r\n");
      out.write("        \r\n");
      out.write("        fd_University_edit.setValue(fd_University_edit.getValue()+':'+fd_University_edit.lastSelectionText);\r\n");
      out.write("        //.set('college_name',fd_University_edit.lastSelectionText);\r\n");
      out.write("        //Ext.getCmp()\r\n");
      out.write("        \r\n");
      out.write("    }); \r\n");
      out.write("    \r\n");
      out.write("    function renderDefault(value, cellmeta, record, rowIndex, columnIndex, store){\r\n");
      out.write("        var editName= '';\r\n");
      out.write("        if (value == null){\r\n");
      out.write("             editName= \"<font color='red'>双击进行编辑</font>\";\r\n");
      out.write("         }else{\r\n");
      out.write("             editName = value ;\r\n");
      out.write("         }    \r\n");
      out.write("        return editName;\r\n");
      out.write("    };\r\n");
      out.write("   var gd_4 = new Ext.grid.EditorGridPanel({\r\n");
      out.write("         //region:'center',\r\n");
      out.write("\t     ds: ds, \t     \r\n");
      out.write("\t     columns:[\r\n");
      out.write("\t     new Ext.grid.CheckboxSelectionModel(),\r\n");
      out.write("\t     {header: \"编号\", width:60,sortable:true,dataIndex: 'newdelcell_seq'},\r\n");
      out.write("\t     {header: \"基站编号\", width:80,sortable:true, dataIndex: 'bureau_id'},\r\n");
      out.write("\t     {header: \"基站名称\", width:80,sortable:true, dataIndex: 'bureau_name'},\r\n");
      out.write("\t     {header: \"校园编号\", width:280,sortable:true, dataIndex: 'college_id',editor:fd_University_edit,renderer:renderDefault},\r\n");
      out.write("\t     {header: \"区编码\", width:60,sortable:true, dataIndex: 'county_code'},\r\n");
      out.write("\t     {header: \"区名称\", width:60,sortable:true, dataIndex: 'county_name'},\r\n");
      out.write("\t     {header: \"营销中心编码\", width:100,sortable:true, dataIndex: 'zone_code'},\r\n");
      out.write("\t     {header: \"营销中心名称\", width:100,sortable:true, dataIndex: 'zone_name'},\r\n");
      out.write("\t     //{header: \"校园名称\", width:170,sortable:true,dataIndex: 'college_name',renderer:renderEditName},\r\n");
      out.write("\t     {header: \"操作者\", width:80,sortable:true,dataIndex: 'operator'}\r\n");
      out.write("\t     ],\r\n");
      out.write("\t     layoutConfig:{\r\n");
      out.write("                    animate:true\r\n");
      out.write("                }, \r\n");
      out.write("\t     bbar : ['->',//new Ext.PagingToolbar({ pageSize: 20, store: ds})\r\n");
      out.write("\t     new Ext.PagingToolbar({id:'pagingtoolbar',pageSize: 30, store: ds,displayInfo: true,loadMask: true,\r\n");
      out.write("displayMsg: '显示第 {0} 条到 {1} 条记录，一共 {2} 条',\r\n");
      out.write("emptyMsg: \"没有记录\",width:480 })\r\n");
      out.write("\t     ],\r\n");
      out.write("\t     loadMask: true,\t\t     \r\n");
      out.write("\t     border:false\r\n");
      out.write("\t     });\r\n");
      out.write("   \r\n");
      out.write("         //Ext.MessageBox.confirm('选择框', resultDate, function(btn) { alert('你刚刚点击了 ' + btn); });\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("      var win = new Ext.Window({   \r\n");
      out.write("        title: \"设置高校基站归属\",    \r\n");
      out.write("        width: 600,\r\n");
      out.write("        height:400,\r\n");
      out.write("        id:'university_win',\r\n");
      out.write("        minWidth: 300,\r\n");
      out.write("        minHeight: 200,\r\n");
      out.write("        layout: 'fit',\r\n");
      out.write("        plain:true,\r\n");
      out.write("        modal: true,\r\n");
      out.write("        bodyStyle:'padding:1px;',\r\n");
      out.write("        buttonAlign:'center',\r\n");
      out.write("             items: [gd_4],   \r\n");
      out.write("             buttons: [{   \r\n");
      out.write("                text: \"确定\", \r\n");
      out.write("                handler: onOKSave,   \r\n");
      out.write("                scope: this  \r\n");
      out.write("            }, {   \r\n");
      out.write("                text: \"退出\",   \r\n");
      out.write("                handler: closeWin,   \r\n");
      out.write("                scope: this  \r\n");
      out.write("            }]   \r\n");
      out.write("  });\r\n");
      out.write("  Ext.MessageBox.yes = \"确定\";\r\n");
      out.write("  Ext.MessageBox.no = \"取消\";\r\n");
      out.write("function onOKSave(){\r\n");
      out.write("//\tif(!fmproc.isValid()){alert('程序信息不完整,请检查');return;};\r\n");
      out.write("  //alert (ds.getCount());\r\n");
      out.write("  var ids = \"\";\r\n");
      out.write("\t\tvar n = document.getElementsByName('cbox').length;\r\n");
      out.write("\t\t//alert(n);\r\n");
      out.write("\t\tfor(var i = 0;i<n;i++){\r\n");
      out.write("\t\t\tif(document.getElementsByName('cbox')[i].checked){\r\n");
      out.write("\t\t\t\tvar id = document.getElementsByName('cbox')[i].value;\r\n");
      out.write("\t\t\t\tif(ids == \"\"){\r\n");
      out.write("\t\t\t\t\tids += id;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tids += \",\" + id;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("  \r\n");
      out.write("  var _sqls = '';\r\n");
      out.write("  for (var i=0;i<ds.getCount();i++){\r\n");
      out.write("       var record = ds.getAt(i);\r\n");
      out.write("      // alert(record.get('college_id'));\r\n");
      out.write("       if (record.get('college_id') == null ){\r\n");
      out.write("          Ext.MessageBox.alert('提示信息!', '未选择对应的高校,请检查数据!', function(btn) { return; });\r\n");
      out.write("       }else{\r\n");
      out.write("          var subUni = record.get('college_id').split(\":\");\r\n");
      out.write("          var _onesql = encodeURIComponent(\"insert into BUREAU_COLLEGE_ORINFO(NEWDELCELL_SEQ,COLLEGE_ID,COLLEGE_NAME,Bureau_ID,operator) values(\"+record.get('newdelcell_seq')+\",'\"+subUni[0]+\"','\"+subUni[1]+\"','\"+record.get('bureau_id')+\"','");
      out.print(userid);
      out.write("')\");\r\n");
      out.write("          _sqls += ((_sqls==''?'':'&') + (\"sqls=\"+_onesql));\r\n");
      out.write("          \r\n");
      out.write("       }     \r\n");
      out.write("  }\r\n");
      out.write("  //Ext.MessageBox.alert('提示信息!', _sqls, function(btn) { return; });\r\n");
      out.write("  \r\n");
      out.write("     var ajax = new aihb.Ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbirs/action/sqlExec?\"+_sqls\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,loadmask : false\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,callback : function(xmlrequest){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t//alert(xmlrequest.responseText);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar _ajax = new aihb.Ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbirs/action/areaSaleManage?method=bureauNewdel\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t,parameters : \"ids=\"+ids+\"&result=succ&eff_type=\"+document.getElementById(\"eff_type\").value\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t,callback : function(xmlrequest){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t    _select_id = '';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tquery();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t//alert(xmlrequest);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t                                           });\r\n");
      out.write("\t\t                                            _ajax.request();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tajax.request();      \r\n");
      out.write("  Ext.getCmp('university_win').hide(); \r\n");
      out.write("  Ext.getCmp('university_win').destroy();     \r\n");
      out.write("};    \r\n");
      out.write("function closeWin(){\r\n");
      out.write("          Ext.getCmp('university_win').hide();\r\n");
      out.write("          Ext.getCmp('university_win').destroy();   \r\n");
      out.write("}; \r\n");
      out.write("}  ;    \r\n");
      out.write("function setUniversityOr(){\r\n");
      out.write("     //alert(\"_select_id:\"+_select_id);\r\n");
      out.write("     if (_select_id.trim()==''){\r\n");
      out.write("        \r\n");
      out.write("\t     \r\n");
      out.write("         return false ;\r\n");
      out.write("     }else{\r\n");
      out.write("         //alert(_select_id);\r\n");
      out.write("         getGridPanel();\r\n");
      out.write("         Ext.getCmp('university_win').show();\r\n");
      out.write("         return true;\r\n");
      out.write("     }\r\n");
      out.write("     return false;\r\n");
      out.write("};      \r\n");
      out.write("var showMask = function(id) {\r\n");
      out.write("\tmask = new Ext.LoadMask(id, {\r\n");
      out.write("\t\tmsg : \"正在处理，请稍候...\",\r\n");
      out.write("\t\tremoveMask : true\r\n");
      out.write("\t});\r\n");
      out.write("\tmask.show();\r\n");
      out.write("};\r\n");
      out.write("var hideMask = function() {\r\n");
      out.write("\tmask.hide();\r\n");
      out.write("};\r\n");
      out.write("\tfunction pass(){\r\n");
      out.write("\t    \r\n");
      out.write("\t\tvar ids = \"\";\r\n");
      out.write("\t\tvar n = document.getElementsByName('cbox').length;\r\n");
      out.write("\t\t//alert(n);\r\n");
      out.write("\t\tfor(var i = 0;i<n;i++){\r\n");
      out.write("\t\t\tif(document.getElementsByName('cbox')[i].checked){\r\n");
      out.write("\t\t\t\tvar id = document.getElementsByName('cbox')[i].value;\r\n");
      out.write("\t\t\t\tif(ids == \"\"){\r\n");
      out.write("\t\t\t\t\tids += id;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tids += \",\" + id;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//加入检查条件\r\n");
      out.write("\t\tif (ids.trim()== \"\" ){\r\n");
      out.write("\t\t    Ext.MessageBox.alert('提示信息!', \"未选择需要审核通过的基站,请先选择!\", function(btn) { return; });\r\n");
      out.write("\t\t    return ;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//加入关联高校的函数\r\n");
      out.write("\t    var _flag = setUniversityOr();\r\n");
      out.write("\t    //alert(_flag);\r\n");
      out.write("\t    //return ;\r\n");
      out.write("\t   \r\n");
      out.write("\t    if (_select_id.trim() == ''){\r\n");
      out.write("\t\t    /**\r\n");
      out.write("\t\t    Ext.MessageBox.confirm('信息提示:', '新增基站审核为非高校基站,请确认！', function(btn) { \r\n");
      out.write("\t\t     if (btn == 'yes'){\r\n");
      out.write("\t\t    \t \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t    showMask(Ext.getBody());\r\n");
      out.write("\t        //alert('开始更新数据！');\r\n");
      out.write("\t        var _ajax = new aihb.Ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbirs/action/areaSaleManage?method=bureauNewdel\"\r\n");
      out.write("\t\t\t,parameters : \"ids=\"+ids+\"&result=succ&eff_type=\"+document.getElementById(\"eff_type\").value\r\n");
      out.write("\t\t\t,callback : function(xmlrequest){\r\n");
      out.write("\t\t\t    _select_id = '';\r\n");
      out.write("\t\t\t\tquery();\r\n");
      out.write("\t\t\t\thideMask();\r\n");
      out.write("\t\t\t\t//alert(xmlrequest);\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t    _ajax.request();\r\n");
      out.write("\t\t\t}else{return false;} \r\n");
      out.write("\t\t     //alert(btn);\r\n");
      out.write("\t\t     });\r\n");
      out.write("\t\t    \t**/\r\n");
      out.write("\t    \tshowMask(Ext.getBody());\r\n");
      out.write("\t\t\tvar _ajax = new aihb.Ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbirs/action/areaSaleManage?method=bureauNewdel\"\r\n");
      out.write("\t\t\t\t,parameters : \"ids=\"+ids+\"&result=succ&eff_type=\"+document.getElementById(\"eff_type\").value\r\n");
      out.write("\t\t\t\t,callback : function(xmlrequest){\r\n");
      out.write("\t\t\t\t\t_select_id = '';\r\n");
      out.write("\t\t\t\t\tquery();\r\n");
      out.write("\t\t\t\t\thideMask();\r\n");
      out.write("\t\t\t\t\t//alert(xmlrequest);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t_ajax.request();\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fail(){\r\n");
      out.write("\t\tvar ids = \"\";\r\n");
      out.write("\t\tvar n = document.getElementsByName('cbox').length;\r\n");
      out.write("\t\tfor(var i = 0;i<n;i++){\r\n");
      out.write("\t\t\tif(document.getElementsByName('cbox')[i].checked){\r\n");
      out.write("\t\t\t\tvar id = document.getElementsByName('cbox')[i].value;\r\n");
      out.write("\t\t\t\tif(ids == \"\"){\r\n");
      out.write("\t\t\t\t\tids += id;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tids += \",\" + id;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tshowMask(Ext.getBody());\r\n");
      out.write("\t\tvar _ajax = new aihb.Ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbirs/action/areaSaleManage?method=bureauNewdel\"\r\n");
      out.write("\t\t\t,parameters : \"ids=\"+ids+\"&result=fail&eff_type=\"+document.getElementById(\"eff_type\").value\r\n");
      out.write("\t\t\t,callback : function(xmlrequest){\r\n");
      out.write("\t\t\t\tquery();\r\n");
      out.write("\t\t\t\thideMask();\r\n");
      out.write("\t\t\t\t//alert(xmlrequest);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t_ajax.request();\t\r\n");
      out.write("\t}\t\r\n");
      out.write("\r\n");
      out.write("\t/**  \r\n");
      out.write("\t * 全选\r\n");
      out.write("\t */\t\r\n");
      out.write("\tfunction selAll(){\r\n");
      out.write("\t\tvar sel = document.getElementsByName('checkAllBox')[0].checked;\r\n");
      out.write("\t\tvar n = document.getElementsByName('cbox').length;\r\n");
      out.write("\t\tif(sel == true){\r\n");
      out.write("\t\t\tfor(var i = 0;i<n;i++){\r\n");
      out.write("\t\t\t\tdocument.getElementsByName('cbox')[i].checked = true;\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tfor(var i = 0;i<n;i++){\r\n");
      out.write("\t\t\t\tdocument.getElementsByName('cbox')[i].checked = false;\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tfunction changetab(id){\r\n");
      out.write("\t\tvar obj=event.srcElement;\r\n");
      out.write("\t\twhile(obj.tagName!=\"TD\") obj=obj.parentElement;\r\n");
      out.write("\t\tvar cellindex=obj.cellIndex;\r\n");
      out.write("\t\twhile(obj.tagName!=\"TABLE\") obj=obj.parentElement;\r\n");
      out.write("\t\tif(obj.lastcell) {obj.rows[0].cells[obj.lastcell].style.backgroundImage=\"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/image/default/tab2.png)\";}\r\n");
      out.write("\t\telse{obj.rows[0].cells[0].style.backgroundImage=\"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/image/default/tab2.png)\";}\r\n");
      out.write("\t\tobj.lastcell=cellindex;\r\n");
      out.write("\t\tobj.rows[0].cells[cellindex].style.backgroundImage=\"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/image/default/tab1.png)\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('selType').value = id;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(\"toDo\" == id){\r\n");
      out.write("\t\t\tif($('passbtn')){\r\n");
      out.write("\t\t\t\t$('passbtn').style.display = \"\";\r\n");
      out.write("\t\t\t\t$('failbtn').style.display = \"\";\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tif($('passbtn')){\r\n");
      out.write("\t\t\t\t$('passbtn').style.display = \"none\";\r\n");
      out.write("\t\t\t\t$('failbtn').style.display = \"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(\"allRec\" == id){\r\n");
      out.write("\t\t\tif($('status_td1')){\r\n");
      out.write("\t\t\t\t//$('status_td1').style.display = \"\";\r\n");
      out.write("\t\t\t\t//$('status_td2').style.display = \"\";\t\r\n");
      out.write("\t\t\t\t$('STATUS').disabled=false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tif($('status_td1')){\r\n");
      out.write("\t\t\t\t//$('status_td1').style.display = \"none\";\r\n");
      out.write("\t\t\t\t//$('status_td2').style.display = \"none\";\t\t\t\t\r\n");
      out.write("\t\t\t\t$('STATUS').disabled=true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\tquery();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction viewDetail(id){\r\n");
      out.write("\t\tvar ids = \"\";\r\n");
      out.write("\t\tvar n = document.getElementsByName('cbox').length;\r\n");
      out.write("\t\tfor(var i = 0;i<n;i++){\r\n");
      out.write("\t\t\tif(document.getElementsByName('cbox')[i].checked){\r\n");
      out.write("\t\t\t\tvar id = document.getElementsByName('cbox')[i].value;\r\n");
      out.write("\t\t\t\tif(ids == \"\"){\r\n");
      out.write("\t\t\t\t\tids += id;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tids += \",\" + id;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar idArr = ids.split(\",\");\t\r\n");
      out.write("\t\tif(ids == \"\"){\r\n");
      out.write("\t\t\talert(\"请先选择一项\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\tif(idArr.length > 1){\r\n");
      out.write("\t\t\talert(\"只能选择一项查看日志\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar _url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbbass/salesmanager/areasale/bureauAudit/bureau_newdel_detail.jsp?id=\"+ids;\r\n");
      out.write("\t\ttabAdd({url:_url,title:'日志'});\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
