/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2017-08-02 09:38:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.hbbass.salesmanager.areasale.bureauAudit;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.asiainfo.hbbass.common.jdbc.ConnectionManage;
import java.sql.*;
import java.sql.SQLException;
import java.sql.PreparedStatement;

public final class college_005fbureau_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String userid = (String)session.getAttribute("loginname");
Connection conn = null;
String region = null;
boolean isProvince = false;
String provinceOperatorCN = null;
String operatorCN = null;
boolean hasRight = false;
try{
	conn = ConnectionManage.getInstance().getWEBConnection();
	
	String sql = "select cityid from FPF_USER_USER where userid='"+userid+"'";
	PreparedStatement ps = conn.prepareStatement(sql);
	ResultSet rs = ps.executeQuery();
	String cityid = null;
	if(rs.next()){
		cityid = rs.getString(1);
		System.out.println("用户的cityid："+cityid);
	}
	
	//如果cityid == 0 ，则是省公司用户，否则为地市用户
	if("0".equals(cityid)){
		isProvince = true;
	}else{
		isProvince = false;
	}
	
	//求出省公司用户该谁审批
	sql = "select OPERATOR,b.username from FPF_AUDIT_FLOW a,FPF_USER_USER b  where a.cityid = '0' and a.operator = b.userid";
	ps = conn.prepareStatement(sql);
	rs = ps.executeQuery();
	String provinceOperator = null;
	provinceOperatorCN = null;
	if(rs.next()){
		provinceOperator = rs.getString(1);
		provinceOperatorCN = rs.getString(2);
		System.out.println("省公司用户该谁审批："+provinceOperatorCN);
		if(userid.equals(provinceOperator)){
			hasRight = true;
		}
	}
	
	//求出地市用户该谁审批
	sql = "select OPERATOR,b.username from FPF_AUDIT_FLOW a,FPF_USER_USER b  where a.cityid = '"+cityid+"' and a.operator = b.userid";
	ps = conn.prepareStatement(sql);
	rs = ps.executeQuery();
	String operator = null;
	operatorCN = null;
	if(rs.next()){
		operator = rs.getString(1);
		operatorCN = rs.getString(2);
		System.out.println("此地区由谁审批："+operatorCN);
		if(userid.equals(operator)){
			hasRight = true;
		}
	}
	
	
	//求出该用户的areaid
	sql = "select b.itemid from FPF_USER_USER a,mk.dim_areacity b where char(a.cityid) = char(b.site_id) and userid='"+userid+"'";
	ps = conn.prepareStatement(sql);
	rs = ps.executeQuery();
	
	if(rs.next()){
		region = rs.getString(1);
		System.out.println("该用户的区域："+region);
	}

	if(isProvince){
		System.out.println("省审批流程为："+provinceOperator);
	}else{
		System.out.println("地市审批流程为："+operatorCN +"-->"+provinceOperatorCN);
	}
	
	rs.close();
	ps.close();
}catch ( SQLException e){
	e.printStackTrace();
}finally{
	if(conn!=null)
		conn.close();
}

      out.write("\t\r\n");
      out.write("<html xmlns:ai>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\">\r\n");
      out.write("\t\t<title>高校新增、删除基站审核</title>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/js/default/default.js\" charset=utf-8></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/js/default/tabext.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/js/default/calendar.js\"></script>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/css/default/default.css\" />\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("var _header=[\r\n");
      out.write("\t{\"name\":\"选择\",\"dataIndex\":\"c0\",cellFunc:\"setId\"}\r\n");
      out.write("\t,{\"name\":\"序列号\",\"dataIndex\":\"c1\"}\r\n");
      out.write("\t,{\"name\":\"地市\",\"dataIndex\":\"c2\"}\r\n");
      out.write("\t,{\"name\":\"县域\",\"dataIndex\":\"c2_2\"}\r\n");
      out.write("\t,{\"name\":\"区域营销中心\",\"dataIndex\":\"c2_3\"}\r\n");
      out.write("\t,{\"name\":\"区域营销中心代码\",\"dataIndex\":\"c2_4\"}\r\n");
      out.write("\t,{\"name\":\"镇\",\"dataIndex\":\"c2_5\"}\r\n");
      out.write("\t,{\"name\":\"基站扇区\",\"dataIndex\":\"c3\"}\r\n");
      out.write("\t,{\"name\":\"高校ID\",\"dataIndex\":\"c4\"}\r\n");
      out.write("\t,{\"name\":\"基站扇区\",\"dataIndex\":\"c5\"}\r\n");
      out.write("\t,{\"name\":\"归属乡镇\",\"dataIndex\":\"c6\"}\r\n");
      out.write("\t,{\"name\":\"导入人员\",\"dataIndex\":\"c7\"}\r\n");
      out.write("\t,{\"name\":\"创建时间\",\"dataIndex\":\"c8\"}\r\n");
      out.write("\t,{\"name\":\"操作类型\",\"dataIndex\":\"c9\"}\r\n");
      out.write("\t,{\"name\":\"状态\",\"dataIndex\":\"c10\"}\t\t\r\n");
      out.write("\t,{\"name\":\"状态时间\",\"dataIndex\":\"c11\"}\r\n");
      out.write("\t//,{\"name\":\"生效类型\",\"dataIndex\":\"c12\"}\r\n");
      out.write("];\r\n");
      out.write("\r\n");
      out.write("function setId(dataIndex,options){\r\n");
      out.write("\tvar str = options.data[options.rowIndex].c1;\r\n");
      out.write("\treturn \"<input type='checkbox' name='cbox' value=\\\"\"+str+\"\\\">\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function genSQL(){\r\n");
      out.write("\tvar selType = $('selType').value;\r\n");
      out.write("\t\r\n");
      out.write("\tvar num = Math.random();\r\n");
      out.write("\t\r\n");
      out.write("\tif(\"toDo\" == selType){\r\n");
      out.write("\t\tvar wherePiece = \" where 1=1 \";\r\n");
      out.write("\t\tif($('OPERATE_TYPE').value != null && $('OPERATE_TYPE').value != \"\"){\r\n");
      out.write("\t\t\twherePiece += \" and OPERATE_TYPE='\"+$('OPERATE_TYPE').value+\"'\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t");

		if(isProvince){//省
		
      out.write("\r\n");
      out.write("\t\t\twherePiece += \" and (STATE='waitaudit2') \";\r\n");
      out.write("\t\t\tif($('areaSel').value != 0){\r\n");
      out.write("\t\t\t\twherePiece += \" and area_code = '\"+$('areaSel').value+\"' \";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t");
	
		}else{//地市
		
      out.write("\r\n");
      out.write("\t\t\twherePiece += \" and (STATE='waitaudit1') \";\r\n");
      out.write("\t\t\twherePiece += \" and area_code = '");
      out.print(region);
      out.write("' \";\r\n");
      out.write("\t\t");

		}
		
      out.write("\r\n");
      out.write("\t\t");

		if(hasRight){//当前用户为审批人
		
      out.write("\r\n");
      out.write("\t\t");
	
		}else{//当前用户不是审批人
		
      out.write("\r\n");
      out.write("\t\t\twherePiece += \" and 1=2\";\r\n");
      out.write("\t\t");

		}
		
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar sql=\"select '' c0,COLLEGEBUREAU_SEQ c1,(select dim.itemname from mk.dim_areacity dim where dim.itemid=area_code) c2,value((select COUNTY_NAME from NWH.DIM_BUREAU_CFG cfg where cfg.BUREAU_ID = info.BUREAU_ID),'') c2_2 ,value((select ZONE_NAME from NWH.DIM_BUREAU_CFG cfg where cfg.BUREAU_ID = info.BUREAU_ID),'') c2_3,value((select ZONE_CODE from NWH.DIM_BUREAU_CFG cfg where cfg.BUREAU_ID = info.BUREAU_ID),'') c2_4,value((select TOWN_NAME from NWH.DIM_BUREAU_CFG cfg where cfg.BUREAU_ID = info.BUREAU_ID),'') c2_5,BUREAU_ID c3,COLLEGE_ID c4,substr(char(CREATE_DATE),1,19) c8,case when operate_type='new' then '新增' when operate_type='del' then '删除' end c9,case when state='waitaudit1' then '待一级审核' when state='waitaudit2' then '待二级审核' when state='succ' then '审核通过'  when state='fail' then '审核不通过'  end c10,substr(char(STATE_DATE),1,19) c11,case when eff_type='0' then '立即生效' when eff_type='1' then '下月生效' end c12 from COLLEGE_BUREAU_INFO info \"\r\n");
      out.write("\t\t\t+ wherePiece\r\n");
      out.write("\t\t\t+ \" and \" + num + \"=\" + num\r\n");
      out.write("\t\t\t+ \" order by c2\"\r\n");
      out.write("\t\t\t+\" with ur\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\treturn sql;\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tif(\"hasDone\" == selType){\r\n");
      out.write("\t\tvar wherePiece = \" and 1=1 \";\r\n");
      out.write("\t\tif($('OPERATE_TYPE').value != null && $('OPERATE_TYPE').value != \"\"){\r\n");
      out.write("\t\t\twherePiece += \" and a.OPERATE_TYPE='\"+$('OPERATE_TYPE').value+\"'\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($('STATE').value != null && $('STATE').value != \"\"){\r\n");
      out.write("\t\t\twherePiece += \" and a.STATE='\"+$('STATE').value+\"'\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t");

		if(isProvince){//省
		
      out.write("\r\n");
      out.write("\t\t\tif($('areaSel').value != 0){\r\n");
      out.write("\t\t\t\twherePiece += \" and a.area_code = '\"+$('areaSel').value+\"' \";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t");
	
		}
		
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar sql=\"select '' c0,a.COLLEGEBUREAU_SEQ c1,(select dim.itemname from mk.dim_areacity dim where dim.itemid=area_code) c2,value((select COUNTY_NAME from NWH.DIM_BUREAU_CFG cfg where cfg.BUREAU_ID = a.BUREAU_ID),'') c2_2 ,value((select ZONE_NAME from NWH.DIM_BUREAU_CFG cfg where cfg.BUREAU_ID = a.BUREAU_ID),'') c2_3,value((select ZONE_CODE from NWH.DIM_BUREAU_CFG cfg where cfg.BUREAU_ID = a.BUREAU_ID),'') c2_4,value((select TOWN_NAME from NWH.DIM_BUREAU_CFG cfg where cfg.BUREAU_ID = a.BUREAU_ID),'') c2_5,BUREAU_ID c3,COLLEGE_ID c4,substr(char(CREATE_DATE),1,19) c8,case when a.operate_type='new' then '新增' when a.operate_type='del' then '删除' end c9,case when state='waitaudit1' then '待一级审核' when state='waitaudit2' then '待二级审核' when state='succ' then '审核通过'  when state='fail' then '审核不通过'  end c10,substr(char(STATE_DATE),1,19) c11,case when eff_type='0' then '立即生效' when eff_type='1' then '下月生效' end c12 from COLLEGE_BUREAU_INFO a,COLLEGE_BUREAU_AUDIT_LOG b where a.COLLEGEBUREAU_SEQ = b.COLLEGEBUREAU_SEQ and b.OPERATOR = '");
      out.print(userid);
      out.write("' \"\r\n");
      out.write("\t\t\t+ wherePiece\r\n");
      out.write("\t\t\t+ \" and \" + num + \"=\" + num\r\n");
      out.write("\t\t\t+ \" order by c2\"\r\n");
      out.write("\t\t\t+\" with ur\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\treturn sql;\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tif(\"allRec\" == selType){\r\n");
      out.write("\t\tvar wherePiece = \" where 1=1 \";\r\n");
      out.write("\t\tif($('OPERATE_TYPE').value != null && $('OPERATE_TYPE').value != \"\"){\r\n");
      out.write("\t\t\twherePiece += \" and OPERATE_TYPE='\"+$('OPERATE_TYPE').value+\"'\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($('STATE').value != null && $('STATE').value != \"\"){\r\n");
      out.write("\t\t\twherePiece += \" and STATE='\"+$('STATE').value+\"'\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t");

		if(isProvince){//省
			
      out.write("\r\n");
      out.write("\t\t\tif($('areaSel').value != 0){\r\n");
      out.write("\t\t\t\twherePiece += \" and area_code = '\"+$('areaSel').value+\"' \";\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t\t");
	
		}else{//地市
		
      out.write("\r\n");
      out.write("\t\t\twherePiece += \" and area_code = '");
      out.print(region);
      out.write("' \";\r\n");
      out.write("\t\t");

		}
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar sql=\"select '' c0,COLLEGEBUREAU_SEQ c1,(select dim.itemname from mk.dim_areacity dim where dim.itemid=area_code) c2,value((select COUNTY_NAME from NWH.DIM_BUREAU_CFG cfg where cfg.BUREAU_ID = info.BUREAU_ID),'') c2_2 ,value((select ZONE_NAME from NWH.DIM_BUREAU_CFG cfg where cfg.BUREAU_ID = info.BUREAU_ID),'') c2_3,value((select ZONE_CODE from NWH.DIM_BUREAU_CFG cfg where cfg.BUREAU_ID = info.BUREAU_ID),'') c2_4,value((select TOWN_NAME from NWH.DIM_BUREAU_CFG cfg where cfg.BUREAU_ID = info.BUREAU_ID),'') c2_5,BUREAU_ID c3,COLLEGE_ID c4,substr(char(CREATE_DATE),1,19) c8,case when operate_type='new' then '新增' when operate_type='del' then '删除' end c9,case when state='waitaudit1' then '待一级审核' when state='waitaudit2' then '待二级审核' when state='succ' then '审核通过'  when state='fail' then '审核不通过'  end c10,substr(char(STATE_DATE),1,19) c11,case when eff_type='0' then '立即生效' when eff_type='1' then '下月生效' end c12 from COLLEGE_BUREAU_INFO info \"\r\n");
      out.write("\t\t\t+ wherePiece\r\n");
      out.write("\t\t\t+ \" and \" + num + \"=\" + num\r\n");
      out.write("\t\t\t+ \" order by c2\"\r\n");
      out.write("\t\t\t+\" with ur\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\treturn sql;\t\r\n");
      out.write("\t}\t\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function query(){\r\n");
      out.write("\tvar grid = new aihb.AjaxGrid({\r\n");
      out.write("\t\theader:_header\r\n");
      out.write("\t\t,sql: genSQL()\r\n");
      out.write("\t\t//,pageSize : 10\r\n");
      out.write("\t});\r\n");
      out.write("\tgrid.run();\r\n");
      out.write("\t/*aihb.AjaxHelper.request({\r\n");
      out.write("\t\theader:_header\r\n");
      out.write("\t\t,url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbirs/action/jsondata?sql=\"+sql\r\n");
      out.write("\t});*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function down(){\r\n");
      out.write("\tvar _fileName=document.title;\r\n");
      out.write("\t\r\n");
      out.write("\taihb.AjaxHelper.down({url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbirs/action/jsondata?method=down&sql=\"+encodeURIComponent(genSQL())+\"&fileName=\"+encodeURIComponent(_fileName)});\r\n");
      out.write("}\r\n");
      out.write("aihb.Util.loadmask();\r\n");
      out.write("window.onload=function(){\r\n");
      out.write("\tvar _d=new Date();\r\n");
      out.write("\t_d.setDate(_d.getDate()-1);\r\n");
      out.write("\t\r\n");
      out.write("\tvar _headerStr=\"\";\r\n");
      out.write("\t\r\n");
      out.write("\tfor(var i=0;i<_header.length;i++){\r\n");
      out.write("\t\tvar header=_header[i];\r\n");
      out.write("\t\tif(_headerStr.length>0){\r\n");
      out.write("\t\t\t_headerStr+=\",\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t_headerStr+=\"\\\"\"+header.dataIndex.toLowerCase()+\"\\\":\\\"\"+header.name+\"\\\"\";\r\n");
      out.write("\t}\r\n");
      out.write("\t_headerStr=\"{\"+_headerStr+\"}\";\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.forms[0].header.value=_headerStr;\r\n");
      out.write("\t\r\n");
      out.write("\tquery();\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t.dim_cell_title_wide {\r\n");
      out.write("\t\tfont-family: \"宋体\";\r\n");
      out.write("\t\tfont-size: 12px;\r\n");
      out.write("\t\tline-height: 20px;\r\n");
      out.write("\t\tfont-weight: normal;\r\n");
      out.write("\t\tfont-variant: normal;\r\n");
      out.write("\t\tcolor: #000000;\r\n");
      out.write("\t\twidth: 20%;\r\n");
      out.write("\t\tbackground-color: #D9ECF6;\r\n");
      out.write("\t}\t\r\n");
      out.write("\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<form method=\"post\" action=\"\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"header\">\r\n");
      out.write("\t\t\t<div class=\"divinnerfieldset\">\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t<legend>\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td onclick=\"hideTitle(this.childNodes[0],'dim_div')\" title=\"点击隐藏\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img flag='1' src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/image/default/ns-expand.gif\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;查询条件区域：\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</legend>\r\n");
      out.write("\t\t\t\t\t<div id=\"dim_div\">\r\n");
      out.write("\t\t\t\t\t\t<table align='center' width='99%' class='grid-tab-blue' cellspacing='1' cellpadding='0' border='0'>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class='dim_row'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='dim_cell_title'>操作类型</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='dim_cell_content'><select id=\"OPERATE_TYPE\"><option value=\"\">全部</option><option value=\"new\">新增</option><option value=\"del\">删除</option></select></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								if(isProvince){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class='dim_cell_title' id=\"area_td1\">地市</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class='dim_cell_content' id=\"area_td2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"areaSel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='0' selected='selected'>全省</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='HB.WH'>武汉</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='HB.HS'>黄石</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='HB.EZ'>鄂州</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='HB.YC'>宜昌</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='HB.ES'>恩施</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='HB.SY'>十堰</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='HB.XF'>襄樊</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='HB.JH'>江汉</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='HB.XN'>咸宁</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='HB.JZ'>荆州</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='HB.JM'>荆门</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='HB.SZ'>随州</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='HB.HG'>黄冈</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='HB.XG'>孝感</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='HB.TM'>天门</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='HB.QJ'>潜江</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

								}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='dim_cell_title' id=\"status_td1\" style=\"display: none\">状态</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='dim_cell_content' id=\"status_td2\" style=\"display: none\"><select id=\"STATE\"><option value=\"\">全部</option><option value=\"waitaudit1\">待一级审核</option><option value=\"waitaudit2\">待二级审核</option><option value=\"waitaudit3\">待三级审核</option><option value=\"succ\">审核通过</option><option value=\"fail\">审核不通过</option></select></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr style=\"display: none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='dim_cell_title_wide' id=\"eff_td1\">审批生效类型(非查询条件，仅供审批使用)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='dim_cell_content' id=\"eff_td2\" colspan=\"5\"><select id=\"eff_type\"><option value=\"\">不更改</option><option value=\"0\" selected=\"selected\">立即生效</option><option value=\"1\">下月生效</option></select></td>\t\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<table align=\"center\" width=\"99%\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"dim_row_submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"form_button\" value=\"查询\" onClick=\"query()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"form_button\" value=\"下载\" onclick=\"down()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"form_button\" value=\"查看日志\" onClick=\"viewDetail()\" id=\"viewDetaibtn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									if(hasRight){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"form_button\" value=\"审批通过\" onClick=\"pass()\" id=\"passbtn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"form_button\" value=\"审批不通过\" onClick=\"fail()\" id=\"failbtn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
	
									}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div class=\"divinnerfieldset\">\r\n");
      out.write("\t\t\t<table><tr><td>本地区的审批流程：\r\n");
      out.write("\t\t\t");
			
			if(isProvince){
				
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.print( provinceOperatorCN);
      out.write("\r\n");
      out.write("\t\t\t\t");

			}else{
				
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.print( operatorCN);
      out.write(" --> ");
      out.print( provinceOperatorCN);
      out.write("\r\n");
      out.write("\t\t\t\t");

			}
			
      out.write("\r\n");
      out.write("\t\t\t</td></tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t<legend>\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td onclick=\"hideTitle(this.childNodes[0],'show_div')\" title=\"点击隐藏\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img flag='1' src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/image/default/ns-expand.gif\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;数据展现区域：\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>全选<input type=\"checkbox\" name=\"checkAllBox\" onclick=\"selAll();\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</legend>\r\n");
      out.write("\t\t    \t\t<table style=\"border-collapse:collapse;border-color:#9AADBE;BACKGROUND-COLOR:#ffffff;border-top:0px;border-bottom:0px;margin-left: 6px\" border=1>\r\n");
      out.write("\t\t\t\t\t<tr height=\"21px\" valign=\"top\" style=\"padding-bottom:0px;padding-top:3px;WIDTH: 10%; border-collapse:collapse;border-color:#9AADBE;BACKGROUND-COLOR:81A3F5\">\r\n");
      out.write("\t\t\t\t\t\t<td  class=\"tab\" background=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/image/default/tab1.png onclick='changetab(\"toDo\");'>&nbsp;待我审核</TD>\r\n");
      out.write("\t\t\t\t\t\t<td  class=\"tab\" background=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/image/default/tab2.png onclick='changetab(\"hasDone\");'>我已审核</TD>\r\n");
      out.write("\t\t\t\t\t\t<td  class=\"tab\" background=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/image/default/tab2.png onclick='changetab(\"allRec\");'>全部记录</TD>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" id=\"selType\" value=\"toDo\">\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"grid\" style=\"display: none;\"></div>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction pass(){\r\n");
      out.write("\t\tvar ids = \"\";\r\n");
      out.write("\t\tvar n = document.getElementsByName('cbox').length;\r\n");
      out.write("\t\tfor(var i = 0;i<n;i++){\r\n");
      out.write("\t\t\tif(document.getElementsByName('cbox')[i].checked){\r\n");
      out.write("\t\t\t\tvar id = document.getElementsByName('cbox')[i].value;\r\n");
      out.write("\t\t\t\tif(ids == \"\"){\r\n");
      out.write("\t\t\t\t\tids += id;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tids += \",\" + id;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar _ajax = new aihb.Ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbirs/action/areaSaleManage?method=collegeBureauNewdel\"\r\n");
      out.write("\t\t\t,parameters : \"ids=\"+ids+\"&result=succ&eff_type=\"+document.getElementById(\"eff_type\").value\r\n");
      out.write("\t\t\t,callback : function(xmlrequest){\r\n");
      out.write("\t\t\t\tquery();\r\n");
      out.write("\t\t\t\t//alert(xmlrequest);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t_ajax.request();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fail(){\r\n");
      out.write("\t\tvar ids = \"\";\r\n");
      out.write("\t\tvar n = document.getElementsByName('cbox').length;\r\n");
      out.write("\t\tfor(var i = 0;i<n;i++){\r\n");
      out.write("\t\t\tif(document.getElementsByName('cbox')[i].checked){\r\n");
      out.write("\t\t\t\tvar id = document.getElementsByName('cbox')[i].value;\r\n");
      out.write("\t\t\t\tif(ids == \"\"){\r\n");
      out.write("\t\t\t\t\tids += id;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tids += \",\" + id;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar _ajax = new aihb.Ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbirs/action/areaSaleManage?method=collegeBureauNewdel\"\r\n");
      out.write("\t\t\t,parameters : \"ids=\"+ids+\"&result=fail&eff_type=\"+document.getElementById(\"eff_type\").value\r\n");
      out.write("\t\t\t,callback : function(xmlrequest){\r\n");
      out.write("\t\t\t\tquery();\r\n");
      out.write("\t\t\t\t//alert(xmlrequest);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t_ajax.request();\t\r\n");
      out.write("\t}\t\r\n");
      out.write("\r\n");
      out.write("\t/**  \r\n");
      out.write("\t * 全选\r\n");
      out.write("\t */\t\r\n");
      out.write("\tfunction selAll(){\r\n");
      out.write("\t\tvar sel = document.getElementsByName('checkAllBox')[0].checked;\r\n");
      out.write("\t\tvar n = document.getElementsByName('cbox').length;\r\n");
      out.write("\t\tif(sel == true){\r\n");
      out.write("\t\t\tfor(var i = 0;i<n;i++){\r\n");
      out.write("\t\t\t\tdocument.getElementsByName('cbox')[i].checked = true;\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tfor(var i = 0;i<n;i++){\r\n");
      out.write("\t\t\t\tdocument.getElementsByName('cbox')[i].checked = false;\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tfunction changetab(id){\r\n");
      out.write("\t\tvar obj=event.srcElement;\r\n");
      out.write("\t\twhile(obj.tagName!=\"TD\") obj=obj.parentElement;\r\n");
      out.write("\t\tvar cellindex=obj.cellIndex;\r\n");
      out.write("\t\twhile(obj.tagName!=\"TABLE\") obj=obj.parentElement;\r\n");
      out.write("\t\tif(obj.lastcell) {obj.rows[0].cells[obj.lastcell].style.backgroundImage=\"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/image/default/tab2.png)\";}\r\n");
      out.write("\t\telse{obj.rows[0].cells[0].style.backgroundImage=\"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/image/default/tab2.png)\";}\r\n");
      out.write("\t\tobj.lastcell=cellindex;\r\n");
      out.write("\t\tobj.rows[0].cells[cellindex].style.backgroundImage=\"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/image/default/tab1.png)\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('selType').value = id;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(\"toDo\" == id){\r\n");
      out.write("\t\t\tif($('passbtn')){\r\n");
      out.write("\t\t\t\t$('passbtn').style.display = \"\";\r\n");
      out.write("\t\t\t\t$('failbtn').style.display = \"\";\t\r\n");
      out.write("\t\t\t\t$('eff_td1').style.display = \"\";\r\n");
      out.write("\t\t\t\t$('eff_td2').style.display = \"\";\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tif($('passbtn')){\r\n");
      out.write("\t\t\t\t$('passbtn').style.display = \"none\";\r\n");
      out.write("\t\t\t\t$('failbtn').style.display = \"none\";\r\n");
      out.write("\t\t\t\t$('eff_td1').style.display = \"none\";\r\n");
      out.write("\t\t\t\t$('eff_td2').style.display = \"none\";\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(\"allRec\" == id){\r\n");
      out.write("\t\t\tif($('status_td1')){\r\n");
      out.write("\t\t\t\t$('status_td1').style.display = \"\";\r\n");
      out.write("\t\t\t\t$('status_td2').style.display = \"\";\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tif($('status_td1')){\r\n");
      out.write("\t\t\t\t$('status_td1').style.display = \"none\";\r\n");
      out.write("\t\t\t\t$('status_td2').style.display = \"none\";\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\tquery();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction viewDetail(id){\r\n");
      out.write("\t\tvar ids = \"\";\r\n");
      out.write("\t\tvar n = document.getElementsByName('cbox').length;\r\n");
      out.write("\t\tfor(var i = 0;i<n;i++){\r\n");
      out.write("\t\t\tif(document.getElementsByName('cbox')[i].checked){\r\n");
      out.write("\t\t\t\tvar id = document.getElementsByName('cbox')[i].value;\r\n");
      out.write("\t\t\t\tif(ids == \"\"){\r\n");
      out.write("\t\t\t\t\tids += id;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tids += \",\" + id;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar idArr = ids.split(\",\");\t\r\n");
      out.write("\t\tif(ids == \"\"){\r\n");
      out.write("\t\t\talert(\"请先选择一项\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\tif(idArr.length > 1){\r\n");
      out.write("\t\t\talert(\"只能选择一项查看日志\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar _url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbbass/salesmanager/areasale/bureauAudit/college_bureau_detail.jsp?id=\"+ids;\r\n");
      out.write("\t\ttabAdd({url:_url,title:'日志'});\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
