/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2017-08-02 09:36:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.hbbass.salesmanager.areasale.bureauAudit;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.asiainfo.hb.web.models.User;

public final class msisdn_005fheader_005fsetting_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>属性维护</title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/js/ext/resources/css/ext-all.css\" />\r\n");
      out.write("\t\t<script type=\"text/javascript\"\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/js/ext/ext-base.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\"\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/js/ext/ext-all.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\"\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/js/default/default.js\"></script>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/js/tooltip/style.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/css/default/default.css\" />\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write(".add {\r\n");
      out.write("\tbackground-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/image/default/add.gif) !important\r\n");
      out.write("\t\t;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".option {\r\n");
      out.write("\tbackground-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/image/default/plugin.gif)\r\n");
      out.write("\t\t!important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".remove {\r\n");
      out.write("\tbackground-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/image/default/delete.gif)\r\n");
      out.write("\t\t!important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".save {\r\n");
      out.write("\tbackground-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/image/default/save.gif)\r\n");
      out.write("\t\t!important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\t\t");

			User user = (User) request.getSession().getAttribute("user");
			String type=request.getParameter("type");
		
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tvar itemsPerPage = 10;\r\n");
      out.write("\t\t\tvar WEB_DS = \"jdbc/WEBDB\";\r\n");
      out.write("\t\t\tvar DW_DS = \"jdbc/DWDB\";\r\n");
      out.write("\t\t\tvar userId='");
      out.print(user.getId());
      out.write("';\r\n");
      out.write("\t\t\tvar type='");
      out.print(type);
      out.write("';\r\n");
      out.write("\t\t\tvar label=\"1\"==type?\"*运营商\":\"*网络制式\";\r\n");
      out.write("\t\t\tvar isAudit=false;\r\n");
      out.write("\t\t\tvar username=['zengguohua','zhaojing','admin'];\r\n");
      out.write("\t\t\tfor(var i=0;i<username.length;i++){\r\n");
      out.write("\t\t\t\tif(userId==username[i]){\r\n");
      out.write("\t\t\t\t\tisAudit=true;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tExt.BLANK_IMAGE_URL = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbapp/resources/js/ext/resources/images/default/s.gif\";\r\n");
      out.write("\t\t\tExt.onReady(function() {\r\n");
      out.write("\t\t\t\tExt.QuickTips.init();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar ispStore = new Ext.data.Store({ \r\n");
      out.write("\t\t\t\t\turl: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jsonData/query\",\r\n");
      out.write("\t\t\t\t\treader : new Ext.data.JsonReader({\r\n");
      out.write("\t\t\t\t\ttotalProperty : 'total',\r\n");
      out.write("\t\t\t\t\troot : 'root'\r\n");
      out.write("\t\t\t\t\t}, [ {\r\n");
      out.write("\t\t\t\t\t\tname : 'id'\r\n");
      out.write("\t\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\t\tname : 'type'\r\n");
      out.write("\t\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\t\tname : 'value'\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t])\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar smb = new Ext.grid.CheckboxSelectionModel({handleMouseDown:Ext.emptyFn});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\tvar cm = new Ext.grid.ColumnModel([new Ext.grid.RowNumberer()\r\n");
      out.write("\t\t\t\t\t\t,smb\r\n");
      out.write("\t\t\t\t\t\t,{header:\"序号\",dataIndex:\"id\",id:\"col\",width:50}\r\n");
      out.write("\t\t\t\t\t\t,{header:\"属性类型\",dataIndex:\"type\",width:250}\r\n");
      out.write("\t\t\t\t\t\t,{header:\"属性值\",dataIndex:\"value\",width:250}\r\n");
      out.write("\t\t\t\t\t\t]);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\tvar gridB = new Ext.grid.GridPanel({\r\n");
      out.write("\t\t\t\t\tid:'gridB',\r\n");
      out.write("\t\t\t\t\tstore:ispStore,\r\n");
      out.write("\t\t\t\t\theight:450,\r\n");
      out.write("\t\t\t\t\tsplit: true,\r\n");
      out.write("\t\t\t\t\tborder:false,\r\n");
      out.write("\t\t\t\t\tautoScroll: true,\r\n");
      out.write("\t\t\t\t\tcm:cm,\r\n");
      out.write("\t\t\t\t\tsm:smb,\r\n");
      out.write("\t\t\t\t\t//autoExpandColumn:'col',\r\n");
      out.write("\t\t\t\t\tloadMask: true,\r\n");
      out.write("\t\t\t\t\ttbar:new Ext.PagingToolbar({\r\n");
      out.write("\t\t\t\t\t\tpageSize:itemsPerPage,\r\n");
      out.write("\t\t\t\t\t\tstore:ispStore,\r\n");
      out.write("\t\t\t\t\t\tbeforePageText : '第',\r\n");
      out.write("\t\t\t\t\t\tafterPageText : '页，共 {0}页',\r\n");
      out.write("\t\t\t\t\t\tdisplayInfo:true,\r\n");
      out.write("\t\t\t\t\t\tdisplayMsg:'显示第{0}条到{1}条记录，一共{2}条记录',\r\n");
      out.write("\t\t\t\t\t\temptyMsg:'无数据'\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tvar toolBarRe = new Ext.Toolbar([\r\n");
      out.write("\t\t\t\t\t{text:'新增',\r\n");
      out.write("\t\t\t\t\ticonCls:'add',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\tif(!isAudit){\r\n");
      out.write("\t\t\t\t\t\t\tExt.MessageBox.show({\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : '信息',\r\n");
      out.write("\t\t\t\t\t\t\t\tmsg : '您不具备操作的权限！',\r\n");
      out.write("\t\t\t\t\t\t\t\tbuttons : Ext.Msg.OK,\r\n");
      out.write("\t\t\t\t\t\t\t\ticon : Ext.MessageBox.ERROR\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\twin.show();\r\n");
      out.write("\t\t\t\t\t\tvar sql=\"select max(id) from ACCHEADER_PROP with ur\";\r\n");
      out.write("\t\t\t\t\t\tvar result=\"\";\r\n");
      out.write("\t\t\t\t\t\tExt.Ajax.request({\r\n");
      out.write("\t\t\t\t\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbirs/action/filemanage?method=checkForWxcs\",\r\n");
      out.write("\t\t\t\t\t\t\tmethod:\"post\",\r\n");
      out.write("\t\t\t\t\t\t\tparams:{sql:sql,ds:'web'},\r\n");
      out.write("\t\t\t\t\t\t\tsuccess:function(response,options){\r\n");
      out.write("\t\t\t\t\t\t\t\tresult=response.responseText;\r\n");
      out.write("\t\t\t\t\t\t\t\tif(result==\"\"||result==null||result==\"null\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tresult=\"1\";\r\n");
      out.write("\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tresult=Number(result)+1;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tExt.getCmp(\"prop_id\").setValue(result);\r\n");
      out.write("\t\t\t\t\t\t\t\tExt.getCmp(\"comboType\").setValue(type==\"\"?\"1\":type);\r\n");
      out.write("\t\t\t\t\t\t\t\tExt.getCmp(\"prop_value\").setValue('');\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}},\r\n");
      out.write("\t\t\t\t\t'-',\r\n");
      out.write("\t\t\t\t\t{text:'修改',\r\n");
      out.write("\t\t\t\t\ticonCls:'option',\r\n");
      out.write("\t\t\t\t\thandler:function(){doUpdate();}},\r\n");
      out.write("\t\t\t\t\t'-',\r\n");
      out.write("\t\t\t\t\t{text:'删除',\r\n");
      out.write("\t\t\t\t\ticonCls:'remove',\r\n");
      out.write("\t\t\t\t\thandler:function(){deleteProp();}}\r\n");
      out.write("\t\t\t\t]);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar formAdd = new Ext.form.FormPanel({\r\n");
      out.write("\t\t\t\t\tlabelAlign:'right',\r\n");
      out.write("\t\t\t\t\tdefaultType:'textfield',\r\n");
      out.write("\t\t\t\t\tlabelWidth:'200',\r\n");
      out.write("\t\t\t\t\tframe:'true',\r\n");
      out.write("\t\t\t\t\tautoHeight:true,\r\n");
      out.write("\t\t\t\t\tid:'propAdd',\r\n");
      out.write("\t\t\t\t\tborder:false,\r\n");
      out.write("\t\t\t\t\titems:[\r\n");
      out.write("\t\t\t\t\t\tnew Ext.form.ComboBox({\r\n");
      out.write("\t\t\t                        fieldLabel: '*类&nbsp;型',\r\n");
      out.write("\t\t\t                        hiddenName:'cType',\r\n");
      out.write("\t\t\t                        hiddenId:'cType',\r\n");
      out.write("\t\t\t                        id:'comboType',\r\n");
      out.write("\t\t\t                        store: new Ext.data.SimpleStore({\r\n");
      out.write("\t\t\t                            fields: ['abbr', 'state'],\r\n");
      out.write("\t\t\t                            data : [\r\n");
      out.write("\t\t\t                            \t\t['1','运营商'],\r\n");
      out.write("\t\t\t                            \t\t['2','网络制式']\r\n");
      out.write("\t\t\t                            \t\t]\r\n");
      out.write("\t\t\t                        }),\r\n");
      out.write("\t\t\t                        valueField:'abbr',\r\n");
      out.write("\t\t\t                        displayField:'state',\r\n");
      out.write("\t\t\t                        typeAhead: true,\r\n");
      out.write("\t\t\t                        mode: 'local',\r\n");
      out.write("\t\t\t                        triggerAction: 'all',\r\n");
      out.write("\t\t\t                        emptyText:'请选择',\r\n");
      out.write("\t\t\t                        disabled:true,\r\n");
      out.write("\t\t\t                        selectOnFocus:true,\r\n");
      out.write("\t\t\t                        width:150,\r\n");
      out.write("\t\t\t                        allowBlank:false\r\n");
      out.write("\t\t\t                    }),\r\n");
      out.write("\t\t\t\t\t\tnew Ext.form.TextField({fieldLabel:'*属性序号',id:'prop_id',width:300,allowBlank:false,disabled:true}),\r\n");
      out.write("\t\t\t\t\t\tnew Ext.form.TextField({fieldLabel:label,id:'prop_value',width:300,allowBlank:false})\r\n");
      out.write("\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\tbuttons:[new Ext.Button({text:'保存',handler:function(){saveProp();}}),\r\n");
      out.write("\t\t\t\t\tnew Ext.Button({text:'返回',handler:function(){win.hide();}})]\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//页面视图\r\n");
      out.write("\t\t\t\tvar viewportCt = new Ext.Viewport({\r\n");
      out.write("\t\t\t\t\tlayout: 'border',\r\n");
      out.write("\t\t\t\t\titems:[\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tregion: 'center',\r\n");
      out.write("\t\t\t\t\t\t\tlayout:\"accordion\",\r\n");
      out.write("\t\t\t\t\t\t\tlayoutConfig: {animate: true},\r\n");
      out.write("\t\t\t\t\t\t\tsplit: true,\r\n");
      out.write("\t\t\t\t\t\t\titems:[\r\n");
      out.write("\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tregion: 'south',\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle:'号头属性维护',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsplit: true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcollapseMode: 'mini',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcollapsible: true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tborder:false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\titems:[toolBarRe,gridB]\r\n");
      out.write("\t\t\t\t\t\t\t\t}]\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfunction query(){\r\n");
      out.write("\t\t\t\t\tif(type==\"\"||type==\"null\"){\r\n");
      out.write("\t\t\t\t\t\ttype=\"1\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tvar sql=\"select id,(case when type=1 then '运营商' when type=2 then '网络制式' end) as type,value from ACCHEADER_PROP where type=\"+type+\" with ur order by id desc\";\r\n");
      out.write("\t\t\t\t\tispStore.load({\r\n");
      out.write("\t\t\t\t\t\tparams:{sql:sql,ds:WEB_DS,start:0,limit:itemsPerPage}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tquery();\r\n");
      out.write("\t\t\t\tfunction saveProp(){\r\n");
      out.write("\t\t\t\t\tvar cType = document.getElementById(\"cType\").value;\r\n");
      out.write("\t\t\t\t\tvar cId = document.getElementById(\"prop_id\").value;\r\n");
      out.write("\t\t\t\t\tvar cValue = document.getElementById(\"prop_value\").value;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(cType == '' || cType == null){\r\n");
      out.write("\t\t\t\t\t\tExt.MessageBox.show({\r\n");
      out.write("\t\t\t\t\t\t\ttitle : '信息',\r\n");
      out.write("\t\t\t\t\t\t\tmsg : '请选择号头属性类型！',\r\n");
      out.write("\t\t\t\t\t\t\tbuttons : Ext.Msg.OK,\r\n");
      out.write("\t\t\t\t\t\t\ticon : Ext.MessageBox.ERROR\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(cValue == '' || cValue == null){\r\n");
      out.write("\t\t\t\t\t\tExt.MessageBox.show({\r\n");
      out.write("\t\t\t\t\t\t\ttitle : '信息',\r\n");
      out.write("\t\t\t\t\t\t\tmsg : '属性值不能为空！',\r\n");
      out.write("\t\t\t\t\t\t\tbuttons : Ext.Msg.OK,\r\n");
      out.write("\t\t\t\t\t\t\ticon : Ext.MessageBox.ERROR\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tExt.Msg.confirm('信息', '确认保存号头属性信息？',function(btn){\r\n");
      out.write("\t\t\t\t\t\tif(btn == 'yes'){\r\n");
      out.write("\t\t\t\t\t\t\tvar mask = new Ext.LoadMask(Ext.getBody(), {\r\n");
      out.write("\t\t\t\t\t\t\t\tmsg : '正在处理数据，请稍候！',\r\n");
      out.write("\t\t\t\t\t\t\t\tremoveMask : true\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\tmask.show();\r\n");
      out.write("\t\t\t\t\t\t\tvar sql=\"insert into ACCHEADER_PROP values(\";\r\n");
      out.write("\t\t\t\t\t\t\tsql+=cId+\",\"+cType+\",'\"+cValue+\"')\";\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tExt.Ajax.request({\r\n");
      out.write("\t\t\t\t\t\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbirs/action/filemanage?method=ddlForWxcs\",\r\n");
      out.write("\t\t\t\t\t\t\t\tmethod:\"post\",\r\n");
      out.write("\t\t\t\t\t\t\t\tparams:{sql:sql,ds:'web'},\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess:function(response,options){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar result=response.responseText;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar msg=\"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(result==\"-1\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmsg=\"操作失败\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmsg=\"操作成功\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tExt.MessageBox.show({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle : '信息',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmsg : msg,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tbuttons : Ext.Msg.OK,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ticon : Ext.MessageBox.INFO\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmask.hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t\twin.hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t\tquery();\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfunction deleteProp(){\r\n");
      out.write("\t\t\t\t\tif(!isAudit){\r\n");
      out.write("\t\t\t\t\t\t\tExt.MessageBox.show({\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : '信息',\r\n");
      out.write("\t\t\t\t\t\t\t\tmsg : '您不具备操作的权限！',\r\n");
      out.write("\t\t\t\t\t\t\t\tbuttons : Ext.Msg.OK,\r\n");
      out.write("\t\t\t\t\t\t\t\ticon : Ext.MessageBox.ERROR\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tvar selections = gridB.getSelectionModel().getSelections();\r\n");
      out.write("\t\t\t\t\t\tif(selections.length == ''){\r\n");
      out.write("\t\t\t\t\t\t\tExt.MessageBox.show({\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : '信息',\r\n");
      out.write("\t\t\t\t\t\t\t\tmsg : '请选中列表记录后再进行删除操作！',\r\n");
      out.write("\t\t\t\t\t\t\t\tbuttons : Ext.Msg.OK,\r\n");
      out.write("\t\t\t\t\t\t\t\ticon : Ext.MessageBox.ERROR\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tExt.Msg.confirm('信息', '确定要删除号头属性信息？', function(btn){\r\n");
      out.write("\t\t\t\t\t\t\tif(btn=='yes'){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar mask = new Ext.LoadMask(Ext.getBody(), {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmsg : '正在加载数据，请稍候！',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tremoveMask : true\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\tmask.show();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar _ids = '';\r\n");
      out.write("\t\t\t\t\t\t\t\tfor(var i = 0;i < selections.length;i++){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar record = selections[i];\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(i == 0){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t_ids += record.get('id');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t_ids += \",\"+record.get('id');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tvar sql=\"delete from ACCHEADER_PROP where id in(\"+_ids+\")\";\r\n");
      out.write("\t\t\t\t\t\t\t\tExt.Ajax.request({\r\n");
      out.write("\t\t\t\t\t\t\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbirs/action/filemanage?method=ddlForWxcs\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmethod:\"post\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\tparams:{sql:sql,ds:'web'},\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsuccess:function(response,options){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar result=response.responseText;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar msg=\"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif(result==\"-1\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmsg=\"操作失败\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmsg=\"操作成功\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tExt.MessageBox.show({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle : '信息',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmsg : msg,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tbuttons : Ext.Msg.OK,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ticon : Ext.MessageBox.INFO\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmask.hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tquery();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfunction doUpdate(){\r\n");
      out.write("\t\t\t\t\tif(!isAudit){\r\n");
      out.write("\t\t\t\t\t\t\tExt.MessageBox.show({\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : '信息',\r\n");
      out.write("\t\t\t\t\t\t\t\tmsg : '您不具备操作的权限！',\r\n");
      out.write("\t\t\t\t\t\t\t\tbuttons : Ext.Msg.OK,\r\n");
      out.write("\t\t\t\t\t\t\t\ticon : Ext.MessageBox.ERROR\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tvar selections = gridB.getSelectionModel().getSelections();\r\n");
      out.write("\t\t\t\t\tif(selections.length == ''){\r\n");
      out.write("\t\t\t\t\t\tExt.MessageBox.show({\r\n");
      out.write("\t\t\t\t\t\t\ttitle : '信息',\r\n");
      out.write("\t\t\t\t\t\t\tmsg : '请选中列表记录后再进行修改操作！',\r\n");
      out.write("\t\t\t\t\t\t\tbuttons : Ext.Msg.OK,\r\n");
      out.write("\t\t\t\t\t\t\ticon : Ext.MessageBox.ERROR\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(selections.length > 1){\r\n");
      out.write("\t\t\t\t\t\t//alert('只能选中一条高校列表记录进行修改操作！');\r\n");
      out.write("\t\t\t\t\t\tExt.MessageBox.show({\r\n");
      out.write("\t\t\t\t\t\t\ttitle : '信息',\r\n");
      out.write("\t\t\t\t\t\t\tmsg : '只能选中一条列表记录进行修改操作！',\r\n");
      out.write("\t\t\t\t\t\t\tbuttons : Ext.Msg.OK,\r\n");
      out.write("\t\t\t\t\t\t\ticon : Ext.MessageBox.ERROR\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tvar record = selections[0];\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\twinU.show();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//Ext.getCmp(\"combouType\").setValue(record.get('type'));\r\n");
      out.write("\t\t\t\t\tif(record.get('type').replace(/(^\\s*)|(\\s*$)/g, \"\")=='运营商'){\r\n");
      out.write("\t\t\t\t\t\tExt.getCmp('combouType').setValue('1');\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tExt.getCmp('combouType').setValue('2');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"uprop_id\").value = record.get('id');\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"uprop_value\").value = record.get('value');\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tfunction updateProp(){\r\n");
      out.write("\t\t\t\t\tvar cType = document.getElementById(\"uType\").value;\r\n");
      out.write("\t\t\t\t\tvar cId = document.getElementById(\"uprop_id\").value;\r\n");
      out.write("\t\t\t\t\tvar cValue = document.getElementById(\"uprop_value\").value;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar sql=\"update ACCHEADER_PROP set type=\"+cType+\",value='\"+cValue+\"' where id=\"+cId;\r\n");
      out.write("\t\t\t\t\tExt.Ajax.request({\r\n");
      out.write("\t\t\t\t\t\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvcPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hbirs/action/filemanage?method=ddlForWxcs\",\r\n");
      out.write("\t\t\t\t\t\t\t\tmethod:\"post\",\r\n");
      out.write("\t\t\t\t\t\t\t\tparams:{sql:sql,ds:'web'},\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess:function(response,options){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar result=response.responseText;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar msg=\"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(result==\"-1\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmsg=\"操作失败\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmsg=\"操作成功\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tExt.MessageBox.show({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle : '信息',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmsg : msg,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tbuttons : Ext.Msg.OK,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ticon : Ext.MessageBox.INFO\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t//mask.hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t\twinU.hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t\tquery();\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t        // Panel for the west\r\n");
      out.write("\t\t        var nav = new Ext.Panel({\r\n");
      out.write("\t\t            region: 'center',\r\n");
      out.write("\t\t            split: true,\r\n");
      out.write("\t\t            width: 200,\r\n");
      out.write("\t\t            collapsible: true,\r\n");
      out.write("\t\t            border:false,\r\n");
      out.write("\t\t            margins:'3 0 3 3',\r\n");
      out.write("\t\t            cmargins:'3 3 3 3',\r\n");
      out.write("\t\t            items:[formAdd]\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t        var win = new Ext.Window({\r\n");
      out.write("\t\t            title: '号头属性新增',\r\n");
      out.write("\t\t            closable:true,\r\n");
      out.write("\t\t            width:500,\r\n");
      out.write("\t\t            height:180,\r\n");
      out.write("\t\t            modal:true,\r\n");
      out.write("\t\t            closeAction:'hide',\r\n");
      out.write("\t\t            //border:false,\r\n");
      out.write("\t\t            plain:true,\r\n");
      out.write("\t\t            layout: 'border',\r\n");
      out.write("\t\t            items: [nav]\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar formU = new Ext.form.FormPanel({\r\n");
      out.write("\t\t\t\t\tlabelAlign:'right',\r\n");
      out.write("\t\t\t\t\tdefaultType:'textfield',\r\n");
      out.write("\t\t\t\t\tlabelWidth:'200',\r\n");
      out.write("\t\t\t\t\tframe:'true',\r\n");
      out.write("\t\t\t\t\tautoHeight:true,\r\n");
      out.write("\t\t\t\t\tid:'collegeAdd',\r\n");
      out.write("\t\t\t\t\tborder:false,\r\n");
      out.write("\t\t\t\t\titems:[\r\n");
      out.write("\t\t\t\t\t\tnew Ext.form.ComboBox({\r\n");
      out.write("\t\t\t                        fieldLabel: '*类&nbsp;型',\r\n");
      out.write("\t\t\t                        hiddenName:'uType',\r\n");
      out.write("\t\t\t                        hiddenId:'uType',\r\n");
      out.write("\t\t\t                        id:'combouType',\r\n");
      out.write("\t\t\t                        store: new Ext.data.SimpleStore({\r\n");
      out.write("\t\t\t                            fields: ['abbr', 'state'],\r\n");
      out.write("\t\t\t                            data : [\r\n");
      out.write("\t\t\t                            \t\t['1','运营商'],\r\n");
      out.write("\t\t\t                            \t\t['2','网络制式']\r\n");
      out.write("\t\t\t                            \t\t]\r\n");
      out.write("\t\t\t                        }),\r\n");
      out.write("\t\t\t                        valueField:'abbr',\r\n");
      out.write("\t\t\t                        displayField:'state',\r\n");
      out.write("\t\t\t                        typeAhead: true,\r\n");
      out.write("\t\t\t                        mode: 'local',\r\n");
      out.write("\t\t\t                        triggerAction: 'all',\r\n");
      out.write("\t\t\t                        emptyText:'请选择',\r\n");
      out.write("\t\t\t                        selectOnFocus:true,\r\n");
      out.write("\t\t\t                        width:150,\r\n");
      out.write("\t\t\t                        allowBlank:false,\r\n");
      out.write("\t\t\t                        disabled:true\r\n");
      out.write("\t\t\t                    }),\r\n");
      out.write("\t\t\t\t\t\tnew Ext.form.TextField({fieldLabel:'*属性序号',id:'uprop_id',width:300,allowBlank:false,disabled:true}),\r\n");
      out.write("\t\t\t\t\t\tnew Ext.form.TextField({fieldLabel:'*属性值',id:'uprop_value',width:300,allowBlank:false})\r\n");
      out.write("\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\tbuttons:[new Ext.Button({text:'保存',handler:function(){updateProp();}}),\r\n");
      out.write("\t\t\t\t\tnew Ext.Button({text:'返回',handler:function(){winU.hide();}})]\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// Panel for the west\r\n");
      out.write("\t\t        var navU = new Ext.Panel({\r\n");
      out.write("\t\t            region: 'center',\r\n");
      out.write("\t\t            split: true,\r\n");
      out.write("\t\t            width: 200,\r\n");
      out.write("\t\t            collapsible: true,\r\n");
      out.write("\t\t            border:false,\r\n");
      out.write("\t\t            margins:'3 0 3 3',\r\n");
      out.write("\t\t            cmargins:'3 3 3 3',\r\n");
      out.write("\t\t            items:[formU]\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t        var winU = new Ext.Window({\r\n");
      out.write("\t\t            title: '号头属性修改',\r\n");
      out.write("\t\t            closable:true,\r\n");
      out.write("\t\t            width:500,\r\n");
      out.write("\t\t            height:180,\r\n");
      out.write("\t\t            modal:true,\r\n");
      out.write("\t\t            closeAction:'hide',\r\n");
      out.write("\t\t            //border:false,\r\n");
      out.write("\t\t            plain:true,\r\n");
      out.write("\t\t            layout: 'border',\r\n");
      out.write("\t\t            items: [navU]\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
